### PR TITLE
Added Add Files Button

### PR DESCRIPTION
**Pull request by platosha**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/6)

### CODE REVIEW

**Comment by jounik** [comment]
@magi42 please review the documentation.

I would encourage us to stop using the code-example element, and use the Polymer demo-snippet element instead.

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[demo/index.html, line 20 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9_xorQRGmdo0VJ9WMT:-K9_xorRAjqdAXcKeWh3:2126410796) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a040861a0630d7cb30acac59e18dba18af441a3b/demo/index.html#L20)):*
ga was here because demos were available in the cdn site, and we wanted to track that.
The removal of this should be discussed with @jounik  and in case remove from all elements demos.

---

*[test/adding-files.html, line 32 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9a-7teOe_DvFER0SXb:-K9a-7tfx9uqoPdymIhv:349849911) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5dda1dca3a85ebbb3af85bf324542c0afe306470/test/adding-files.html#L32)):*
add button? we might have more buttons in the future

---

*[test/adding-files.html, line 35 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9a21Jl4cLsJj68gdD4:-K9a21Jmcizu1bE872X-:315640858) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5dda1dca3a85ebbb3af85bf324542c0afe306470/test/adding-files.html#L35)):*
I would write a comment here saying that the dialog is actually not opened because of security reasons (fired async), and actually we are testing that we actually fire the click event.

---

*[test/adding-files.html, line 44 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9a3kx-dkzORgYaSmGM:-K9a3kx0fH0ZdvR5A9Jn:-479534879) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5dda1dca3a85ebbb3af85bf324542c0afe306470/test/adding-files.html#L44)):*
I would test that file has name, and size

---

*[test/adding-files.html, line 48 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9a2QPoJLxdFqreEus5:-K9a2QPoJLxdFqreEus6:-659639312) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5dda1dca3a85ebbb3af85bf324542c0afe306470/test/adding-files.html#L48)):*
Can you use the common.createFiles and remove the TODO? something like 

files = createFiles(2, 1024, 'application/x-binary')

Then it's clear than we are assigning a set of files

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[demo/index.html, line 20 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9_xorQRGmdo0VJ9WMT:-K9a54uSSTQzwO_LJxqh:-530209129) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a040861a0630d7cb30acac59e18dba18af441a3b/demo/index.html#L20)):*
never mind, ga is in common

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6)*

**Comment by jounik** [comment]
*[demo/index.html, line 20 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9_xorQRGmdo0VJ9WMT:-K9a67r9dSgyWD5eNYqf:1710183407) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a040861a0630d7cb30acac59e18dba18af441a3b/demo/index.html#L20)):*
No need to track these anymore, as these should not be linked to from anywhere. So do not put too much effort in the demos in the development repo, we’ll let the marketing team prepare the official demos for vaadin.com/elements page.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6)*

**Comment by jounik** [comment]
*[demo/index.html, line 20 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9_xorQRGmdo0VJ9WMT:-K9aYGH7UNliHrt6K4z9:1627406004) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a040861a0630d7cb30acac59e18dba18af441a3b/demo/index.html#L20)):*
I feel we should stop using the whole element-demo-resources package, and start adopting the paper-styles and demo-snippet stuff that Polymer is using, so we are aligned with them. For example https://github.com/polymerelements/paper-button/blob/master/demo/index.html

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6)*

**Comment by platosha** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/adding-files.html, line 32 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9a-7teOe_DvFER0SXb:-K9azYL02yaxU2QY-LKa:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5dda1dca3a85ebbb3af85bf324542c0afe306470/test/adding-files.html#L32)):*
Done.

---

*[test/adding-files.html, line 35 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9a21Jl4cLsJj68gdD4:-K9azZJk9bi4mSVxY5lV:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5dda1dca3a85ebbb3af85bf324542c0afe306470/test/adding-files.html#L35)):*
Done.

---

*[test/adding-files.html, line 44 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9a3kx-dkzORgYaSmGM:-K9azZtxvmzL9WM8WHsY:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5dda1dca3a85ebbb3af85bf324542c0afe306470/test/adding-files.html#L44)):*
Done.

---

*[test/adding-files.html, line 48 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9a2QPoJLxdFqreEus5:-K9aza5mlivImfb7NJX0:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5dda1dca3a85ebbb3af85bf324542c0afe306470/test/adding-files.html#L48)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6)*

**Comment by manolo** [comment]
Reviewed 6 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6)*

**Comment by magi42** [comment]
Reviewed 2 of 7 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions, all commit checks successful.

---

*[demo/index.html, line 31 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9b-e0uLZct28RIg25v:-K9b-e0vKn7ohvbqdytB:1128391247) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5dda1dca3a85ebbb3af85bf324542c0afe306470/demo/index.html#L31)):*
(I started thinking here if element names are proper names, in which case it should not have definite article. On the other hand, first letters of sentences should always be capitalized. However, it seems that they are generally not considered proper names, but rather written as: "The `div` element...". So, this is OK.)

For another open question, I've usually written element names with angle brackets, such as, `<vaadin-upload>`. Some documentation, such as W3Schools, uses this convention, while in W3C specs, element names are written without. Wikipedia is somewhat mixed, at least when making a distinction between elements and tags. For example, "_The `div` element begins with a `<div>` tag_." We'll have to think about this convention better, so for now just let it be.

---

*[demo/index.html, line 36 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bAVT19CcsST43rzy7:-K9bAVT19CcsST43rzy8:-1702059515) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5dda1dca3a85ebbb3af85bf324542c0afe306470/demo/index.html#L36)):*
Maybe add something explanatory before code example. What's the "demo" in the start tag? Maybe explain that as well.

"You use `vaadin-upload` as an empty element."

---

*[demo/index.html, line 44 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bBP8FbgfihPWCMKIY:-K9bBP8FbgfihPWCMKIZ:1267711981) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5dda1dca3a85ebbb3af85bf324542c0afe306470/demo/index.html#L44)):*
Again some even short explanation would be nice to have.

For example:
"When files are added by the user, the `vaadin-upload`element sends `file-add` events. You can listen for them by adding an event listener to the element. The `event.detail.file` object contains details about the file to be uploaded, namely its `name` and `size`."

Is there just this one event or are there more?

---

*[docs/overview.asciidoc, line 11 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bKLlUv5x7z8CZlSz6:-K9bKLlUv5x7z8CZlSz7:-817579536) ([raw file](https://github.com/vaadin/vaadin-upload/blob/df8ef039b75e82ff99c77593012104a262ae95ab/docs/overview.asciidoc#L11)):*
I think the server is definite there: "files to _the_ server."

---

*[docs/overview.asciidoc, line 13 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bDyBv02wqifE_yIuf:-K9bDyBwUsjYGwg8imYR:-1165047824) ([raw file](https://github.com/vaadin/vaadin-upload/blob/df8ef039b75e82ff99c77593012104a262ae95ab/docs/overview.asciidoc#L13)):*
* Word "their" is maybe unnecessary here. Maybe just say: "It allows users to upload files simply by dropping them into the component." (Is it a component or element?)
* Not sure if that should be "into" or "onto"... maybe just let it be like that.
* "Also" is here an introductory clause and should have a comma following it. (Otherwise difficult to distinguish between "Also it" and "It has".)
* However, the word order probably show be: "_It also has_".
* I'd say "Add Files" button is indefinite here, so "_an Add Files button_"
* For emphasizing button names, use `[guibutton]#Add Files#`.
* Perhaps rather "to process" -> "to _upload_".
* Formatting note: while I'm not requiring it, you could try using sentence-per-line. I've found it makes organizing the sentences a bit easier – you could consider it and see how it works for you.

---

*[docs/overview.asciidoc, line 15 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bGIbkUvXpG5VnyPXU:-K9bGIbkUvXpG5VnyPXV:-1156728111) ([raw file](https://github.com/vaadin/vaadin-upload/blob/df8ef039b75e82ff99c77593012104a262ae95ab/docs/overview.asciidoc#L15)):*
* _the_ user

---

*[docs/overview.asciidoc, line 17 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bG_2QiYOPln8oKwQe:-K9bG_2RmJ3VcALLrsx2:-676764455) ([raw file](https://github.com/vaadin/vaadin-upload/blob/df8ef039b75e82ff99c77593012104a262ae95ab/docs/overview.asciidoc#L17)):*
* "Uploading the the added files to the server starts automatically."
* "~~The~~ Uploading of..."

---

*[docs/overview.asciidoc, line 19 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bH9xAjOvJVNXqXBBC:-K9bH9xAjOvJVNXqXBBD:-547958184) ([raw file](https://github.com/vaadin/vaadin-upload/blob/df8ef039b75e82ff99c77593012104a262ae95ab/docs/overview.asciidoc#L19)):*
* _can_ be removed
* _the_ user
* Rather: "If pressed while the file upload is in progress..."
* ", ~~then~~ the"

---

*[docs/overview.asciidoc, line 21 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bHg_QHX2I8ccAcowq:-K9bHg_Rvqbx-QgTmUfq:-661677322) ([raw file](https://github.com/vaadin/vaadin-upload/blob/df8ef039b75e82ff99c77593012104a262ae95ab/docs/overview.asciidoc#L21)):*
Write at least something introductory here, such as:

"The element is used as a plain empty element as follows:"

Again, what was the empty "demo" attribute in another file?

---

*[docs/overview.asciidoc, line 29 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bHxFiiqBM3-YsqwWn:-K9bHxFiiqBM3-YsqwWo:-347165699) ([raw file](https://github.com/vaadin/vaadin-upload/blob/df8ef039b75e82ff99c77593012104a262ae95ab/docs/overview.asciidoc#L29)):*
* "The `vaadin-upload`element..."
* Comma before "as well".

---

*[docs/overview.asciidoc, line 35 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bIAB-_pv8LpxBDHqO:-K9bIAB-_pv8LpxBDHqP:-976043749) ([raw file](https://github.com/vaadin/vaadin-upload/blob/df8ef039b75e82ff99c77593012104a262ae95ab/docs/overview.asciidoc#L35)):*
Events when file removed  and upload state changes were mentioned above, but not listed here.
If such events are not yet implemented, could // outcomment the mention earlier.

* "when _a_ file is added"
* "into" -> "onto"? (Not sure, maybe not)
* `[guibutton]#Add Files#`

---

*[docs/overview.asciidoc, line 39 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bIXfMJZMylK2990Np:-K9bIXfMJZMylK2990Nq:-2063530306) ([raw file](https://github.com/vaadin/vaadin-upload/blob/df8ef039b75e82ff99c77593012104a262ae95ab/docs/overview.asciidoc#L39)):*
File and XMLHttpRequest are a sort of class names, for which `[classname]#File#` and `[classname]#XMLHttpRequest#`emphasis should be used. There's currently no emphasis style for properties – maybe just do as it is for now.

---

*[docs/overview.asciidoc, line 41 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bJ5vK7hQzqrl6Vhr6:-K9bJ5vK7hQzqrl6Vhr7:-1194229874) ([raw file](https://github.com/vaadin/vaadin-upload/blob/df8ef039b75e82ff99c77593012104a262ae95ab/docs/overview.asciidoc#L41)):*
Method names should use the `[methodname]#addEventListener()#` emphasis markup. Please note to use parentheses after method names.

---

*[docs/overview.asciidoc, line 53 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6#-K9bJNbHuonok3R1i6sk:-K9bJNbHuonok3R1i6sl:-238450241) ([raw file](https://github.com/vaadin/vaadin-upload/blob/df8ef039b75e82ff99c77593012104a262ae95ab/docs/overview.asciidoc#L53)):*
* ..."when using _the element_ inside"...
* ..."_the_ declarative binding syntax"...
* What's a "hosting element method"? I don't understand what that is.
* The sentence is a bit long and complex.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/6)*

**Comment by manolo** [comment]
@magi42 picked up all your comments and almost applied in the other review #25 , can you take a look?

**Pull request merged**
