### PR TITLE
Fix: Drag over disabling click

### LINKED ISSUE #107: Dropping a file on a nodrop element will disable the button.
Recreate: try to drop an item on the nodrop element (https://cdn.vaadin.com/vaadin-elements/master/vaadin-upload/demo/)
Then try to click the button.

The drop should not be allowed, but the button should remain active for further use.

### PR DESCRIPTION
**Pull request by stramel**
Should fix #107

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/150)

### CODE REVIEW

**Comment by stramel** [comment]
CLA has been signed but I'm not sure why it isn't showing

**Comment by jouni** [comment]
I just checked from cla-assistant.io and I can see you’ve signed the CLA (already back on Jan 17th). Not sure why it’s bugging here. But anyway, thanks for the PR, I’ll ping the team to take a look asap.

**Comment by manolo** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 538 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/150#-KboQv0gf3hFQoQM3-8_:-KboQv0gf3hFQoQM3-8a:b-fhrk4k) ([raw file](https://github.com/vaadin/vaadin-upload/blob/b73fc46f888e96c740ce0beb163dcf9872180eb4/vaadin-upload.html#L538)):*
> ```HTML
>         }
>         this._dragover = true;
>       }
> ```

I think this logic could be simplified, like : 

```
      if (!this.nodrop && !this._dragover) {
        this._dragoverValid = !this._maxFilesAdded();
        if (this._dragoverValid) {
          this._dragRippleAction('down', event);
        }
        this._dragover = true;
      }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/150)*

**Comment by stramel** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 538 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/150#-KboQv0gf3hFQoQM3-8_:-KbpCoKnJRTevLGeW_6t:b-ax2tpf) ([raw file](https://github.com/vaadin/vaadin-upload/blob/b73fc46f888e96c740ce0beb163dcf9872180eb4/vaadin-upload.html#L538)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think this logic could be simplified, like : 

```
      if (!this.nodrop && !this._dragover) {
        this._dragoverValid = !this._maxFilesAdded();
        if (this._dragoverValid) {
          this._dragRippleAction('down', event);
        }
        this._dragover = true;
      }
```
</blockquote></details>

Good catch! Fix pushed and tests still passing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/150)*

**Comment by stramel** [comment]
@jouni I had made the push from my work email and I had signed it using my personal email. Adding my work email to this account and pushing a change seems to have fixed it. I notice that google's CLA bot re-checks on comments as well, maybe a way to fix it for your bot?

**Comment by manolo** [comment]
:lgtm_strong:  Thanks for contributing

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/150#-:-Kbpjqb7_2vETHZevy_5:bavy733)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/150#-:-KbsvaUOMvDNE8xA45RK:bnfp4nl)*

**Pull request merged**
