### PR TITLE
Include a static getter for the element version

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/224)

### CODE REVIEW

**Comment by limonte** [comment]
- bash scripts in the root folder of the front-end component looks strange. Maybe a `tools` folder for them?
- spaces or tabs, it doesn't matter, but please do not use both at the same time.

**Comment by Artur-** [comment]
Moved scripts to `tools`, changed to spaces and to use some node modules instead of `jq` and `sed`

**Comment by manolo** [comment]
I think having external scripts for this is not good for maintenance, even in a subfolder.
You could do everything in just one line in both `package.json` and `.travis.yml` (I did a prototype in this branch: https://github.com/vaadin/vaadin-upload/compare/check-version?expand=1)
Otherwise I would suggest, to add both tasks in the `gulpfile.js` (since we already use this), it would make easier for running checks in local, or add those scripts in a external npm project so as all our elements depend on it.

---

Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/checkVersionGetter.sh, line 3 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo2wHWCfkoHvZs9dKo:-Kyo2wHWCfkoHvZs9dKp:b-6rdqwm) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/tools/checkVersionGetter.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> npmVersion=$(node -e "console.log(require('./package.json').version)")
> ```

Using back-ticks instead of `$()` would work in normal shell not only bash

---

*[tools/checkVersionGetter.sh, line 4 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo2iMCiT4vSpn9w2kn:-Kyo2iMCiT4vSpn9w2ko:blj58zf) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/tools/checkVersionGetter.sh#L4)):*
> ```Shell
> 
> npmVersion=$(node -e "console.log(require('./package.json').version)")
> offendingVersions=$(grep 'static get version()' *.html -A1|grep return|grep -v "return '$npmVersion';")
> ```

using grep instead of `grep -v` you can use the exit code instead of checking and empty  string

---

*[tools/checkVersionGetter.sh, line 6 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo32bkqEQox9GTEXTN:-Kyo32bkqEQox9GTEXTO:bbnxakf) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/tools/checkVersionGetter.sh#L6)):*
> ```Shell
> offendingVersions=$(grep 'static get version()' *.html -A1|grep return|grep -v "return '$npmVersion';")
> 
> if [ "$offendingVersions" != "" ]
> ```

tip `[ -n "$foo" ]` 

---

*[tools/updateElementVersions.js, line 3 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo1VPGvGSg4VboCNDg:-Kyo1VPGvGSg4VboCNDh:bqpgm1r) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/tools/updateElementVersions.js#L3)):*
> ```JavaScript
> #!/usr/bin/env node
> 
> oldversion=require('../package.json').version;
> ```

you need to define the variable add `const` or better inline both in the options block

---

*[tools/updateElementVersions.js, line 6 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo1cqK-B4Y83yCw36i:-Kyo1cqK-B4Y83yCw36j:b59fefz) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/tools/updateElementVersions.js#L6)):*
> ```JavaScript
> newversion=process.env.npm_package_version
> 
> const replace = require('replace-in-file');
> ```

This need to be added as dependency in `package.json`

---

*[tools/updateElementVersions.js, line 8 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo06zfuCjsmZCgyNkc:-Kyo06zfuCjsmZCgyNkd:b-8qkiwt) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/tools/updateElementVersions.js#L8)):*
> ```JavaScript
> const replace = require('replace-in-file');
> const options = {
>   files: '*.html',
> ```

modifying all files sounds bad, a developer could have files here not in git. Use `${npm_package_name}.html` instead.

---

*[tools/updateElementVersions.js, line 15 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo2GsS9vr01ZFiIb41:-Kyo2GsT8odIp_zh7OOd:b9lncnp) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/tools/updateElementVersions.js#L15)):*
> ```JavaScript
> try {
>   const updatedFiles = replace.sync(options);
>   const simpleGit = require('simple-git')(".");
> ```

You need to add this dependency as well.
Also, move all imports to the top of the file

---

*[tools/updateElementVersions.js, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo0iMaxPvcxiI3--SD:-Kyo0iMaxPvcxiI3--SE:b-ny1qtm) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/tools/updateElementVersions.js#L19)):*
> ```JavaScript
>   console.log('Modified files:', updatedFiles.join(', '));
> }
> catch (error) {
> ```

should be in the same line than the closing bracket

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-:-KynzRkn7ANp-ux00r-1:b-bsx8pb)*

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[tools/updateElementVersions.js, line 14 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo3bVzue9sATqznySt:-Kyo3bVzue9sATqznySu:b79gys6) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/tools/updateElementVersions.js#L14)):*
> ```JavaScript
> 
> try {
>   const updatedFiles = replace.sync(options);
> ```

it seems that `replace` 

---

*[tools/updateElementVersions.js, line 17 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo4IaaUwIIU4TtONvE:-Kyo4IaaUwIIU4TtONvF:bldq756) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/tools/updateElementVersions.js#L17)):*
> ```JavaScript
>   const simpleGit = require('simple-git')(".");
>   simpleGit.add(updatedFiles);
>   console.log('Modified files:', updatedFiles.join(', '));
> ```

tip you don't need to use `join` if you add an array to a string in JS, hence this could be
`console.log('Modified files: ' +  updatedFiles); `

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224)*

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[.travis.yml, line 33 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo4gdCh7Nu_EQeVEOo:-Kyo4gdCh7Nu_EQeVEOp:b5r904a) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/.travis.yml#L33)):*
> ```YAML
>       xvfb-run -s '-screen 0 1024x768x24' polymer test --env saucelabs-cron;
>     fi
>   - tools/checkVersionGetter.sh
> ```

move this line to the before_script block, so the build fails earlier and we don't need to wait for all tests being run

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224)*

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[tools/updateElementVersions.js, line 14 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo3bVzue9sATqznySt:-KyoLgtJoSuYQRINg18g:b-kl00k6) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/tools/updateElementVersions.js#L14)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

it seems that `replace` 
</blockquote></details>

Not a valid comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224)*

**Comment by Artur-** [comment]
Changed to gulp tasks

---

Review status: 0 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[.travis.yml, line 33 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyo4gdCh7Nu_EQeVEOo:-Kytl0GvC4rrd8VGRDUl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5887b06058980573f539bb6792454c3aaff8e0f2/.travis.yml#L33)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

move this line to the before_script block, so the build fails earlier and we don't need to wait for all tests being run
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-:-KytkxB9uPW2xzr1BITK:bvwep84)*

**Comment by manolo** [comment]
wow, much better now

---

Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[.travis.yml, line 20 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kytrgkb6nXaZgkMTiAR:-Kytrgkb6nXaZgkMTiAS:b-ywm2k7) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2b9a88c3af5ba7799eb76ef3d79206595ef05871/.travis.yml#L20)):*
> ```YAML
> before_script:
>   - gulp lint
>   - gulp version:check
> ```

nit: you can run both tasks at the same time so as gulp command is only run once

---

*[gulpfile.js, line 59 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-KytrPcAWF5Tw1SRAO7h:-KytrPcAWF5Tw1SRAO7i:b5vfgyy) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2b9a88c3af5ba7799eb76ef3d79206595ef05871/gulpfile.js#L59)):*
> ```JavaScript
> gulp.task('version:check', function() {
>   const expectedVersion = new RegExp('^' + require('./package.json').version + '$');
>   return gulp.src(['*.html'])
> ```

Still not convinced on visiting all files. I guess we should maintain the static version only in the main component of the repo, in this case vaadin-upload, or in the case of grid vaadin-grid, and so on. 

---

*[gulpfile.js, line 79 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyts6AnVjqho_H2r-8x:-Kyts6AoofEPOj-Wnpxz:b-v3dgps) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2b9a88c3af5ba7799eb76ef3d79206595ef05871/gulpfile.js#L79)):*
> ```JavaScript
>     throw new 'New version must be given as a npm_package_version environment variable.';
>   }
>   return gulp.src(['*.html'])
> ```

Modifying just the specific file given by  npm_package_name.html sounds more reliable to me. Otherwise if we want to have it in other  elements in the repo like e.g vaadin-password-field, it would be nice to filter like you do in the other task (find, clip) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-:-KytuUl307MkiIyDgLeN:bkhm54b)*

**Comment by Artur-** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[gulpfile.js, line 59 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-KytrPcAWF5Tw1SRAO7h:-Kyu8YEDWitKl-Ks5vkJ:bzhwtk1) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2b9a88c3af5ba7799eb76ef3d79206595ef05871/gulpfile.js#L59)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Still not convinced on visiting all files. I guess we should maintain the static version only in the main component of the repo, in this case vaadin-upload, or in the case of grid vaadin-grid, and so on. 
</blockquote></details>

I would still go through all files here so you do not have to maintain a separate list for where the version is (there is no harm in going through all files, I find it extremely unlikely that another HTML file would have a `static get version` used for another purpose)

---

*[gulpfile.js, line 79 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kyts6AnVjqho_H2r-8x:-Kyu9f_avaXr-2UksaIt:b-ql2qcr) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2b9a88c3af5ba7799eb76ef3d79206595ef05871/gulpfile.js#L79)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Modifying just the specific file given by  npm_package_name.html sounds more reliable to me. Otherwise if we want to have it in other  elements in the repo like e.g vaadin-password-field, it would be nice to filter like you do in the other task (find, clip) 
</blockquote></details>

My thoughts was pretty much the same as above - if the version number is mentioned in some comment or similar, we would want to update that also. From my understanding `replace` will be a no-op if there is no match so is there gain in adding `find` and`clip`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224)*

**Comment by Artur-** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[.travis.yml, line 20 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-Kytrgkb6nXaZgkMTiAR:-KyuACpLTgvuIHl6RWnC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2b9a88c3af5ba7799eb76ef3d79206595ef05871/.travis.yml#L20)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

nit: you can run both tasks at the same time so as gulp command is only run once
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 6 of 8 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-:-KyuxZ2yQhdqXkVYPT8a:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[gulpfile.js, line 68 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-KyyTSmFjr0MbA4Q4M5C:-KyyTSmFjr0MbA4Q4M5D:b-6eyw0) ([raw file](https://github.com/vaadin/vaadin-upload/blob/86d3e4fb74f8f86ed9ec7c1fe7d1fe51ed6724f6/gulpfile.js#L68)):*
> ```JavaScript
> });
> 
> gulp.task('version:update', function() {
> ```

I guess we can check the version before the update to make sure that version is ok in element before making the replacement

```
gulp.task('version:update', ['version:check'], function() {
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224)*

**Comment by manolo** [comment]
:lgtm_strong:  good job !

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/224#-:-Kyylm6Luj0GW6YOmv11:b3zfcmg)*

**Pull request merged**
