### PR TITLE
New: Add ability to start upload for file-list

### PR DESCRIPTION
**Pull request by stramel**
image

Adds ability to start a file upload from the file-list

### TODO:

- [x] Tests

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/192)

### CODE REVIEW

**Comment by stramel** [comment]
@saulis @manolo PTAL

**Comment by platosha** [comment]
Good job, thanks!

:lgtm: overall

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload-file.html, line 240 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/192#-Kl2cwDpyWOssxJgGrSk:-Kl2cwDpyWOssxJgGrSl:bbrb03h) ([raw file](https://github.com/vaadin/vaadin-upload/blob/930d26c086fbec01d52536a29da8ee540fbb68f9/vaadin-upload-file.html#L240)):*
> ```HTML
> 
>     <paper-progress
>       id="progress"
> ```

Unnecessary formatting change here and down. Please revert.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/192#-:-Kl2dhOG2xWNKvhD6Xxm:b-ul2ua)*

**Comment by stramel** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload-file.html, line 240 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/192#-Kl2cwDpyWOssxJgGrSk:-Kl5RfXaftD3UXEEc84C:b2ti096) ([raw file](https://github.com/vaadin/vaadin-upload/blob/930d26c086fbec01d52536a29da8ee540fbb68f9/vaadin-upload-file.html#L240)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Unnecessary formatting change here and down. Please revert.
</blockquote></details>

Sorry, did it out of habit. Updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/192)*

**Comment by stramel** [comment]
Just realized I haven't added tests yet. I will add some :)

**Comment by stramel** [comment]
@platosha @manolo @Saulis Ping :)

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/192#-:-Km5kKidoTikaSJTBYlC:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-upload-file.html, line 152 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/192#-Km5jjOsEUWulDpj2rTB:-Km5jjOsEUWulDpj2rTC:b-j0dcfe) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9f93678270ab9e8dd41c312811a93c8f0d5ec24c/vaadin-upload-file.html#L152)):*
> ```HTML
> 
>       #commands [icon="vaadin-upload:refresh"],
>       #commands [icon="vaadin-upload:clear"] {
> ```

Add a selector for the new button here as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/192)*

**Comment by stramel** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-upload-file.html, line 152 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/192#-Km5jjOsEUWulDpj2rTB:-Km77bfu28ORpbTmOUCo:b-yh16lj) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9f93678270ab9e8dd41c312811a93c8f0d5ec24c/vaadin-upload-file.html#L152)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Add a selector for the new button here as well
</blockquote></details>

Done. Good call!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/192)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/192#-:-KmBAG_-6YnmaZ8vMMCK:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/192#-:-KmBCsTocWzKLhIyPvvA:bnfp4nl)*

**Comment by stramel** [comment]
@platosha @tomivirkki @manolo @Saulis @jouni Ping. Looks like I have plenty of approvals.

**Comment by jouni** [comment]
Sorry for taking such a long time processing this.

I’m not against this enhancement. I just haven’t had time to consider how this affects different use cases. But I trust you have considered the most obvious ones at least, that there aren’t any confusing situations what should happen when certain buttons are pressed during the lifecycle of an upload.

I also haven’t had time to consider how this works with the idea I outlined in https://github.com/vaadin/vaadin-upload/issues/196#issuecomment-306785047, about splitting this element into composable parts (vaadin-file-chooser, vaadin-upload-list, vaadin-uploader) (hint: if you want to prototype that, it would be appreciated).

So a LGTM from me as well.

**Comment by stramel** [comment]
@jouni I did do a quick smoke test of the new feature and everything seemed normal.

WRT breaking into more composable parts, I can definitely take a stab at it. Is there anything else you think should be included in it? Maybe we should open an issue and move this discussion over there? I would like to see composability and start/pause capability. Maybe the promise stuff that @platosha had talked about in another PR.

**Comment by jouni** [comment]
A new issue is in order to discuss the split-up. I can so that probably tomorrow and put my initial ideas in it.

**Comment by jouni** [comment]
Well, that took a bit longer than I intended, but I finally wrote down the issue about the modularization: #201 

Still regarding this issue, I hope @manolo and @platosha can agree if this is ready to be merged. I’m okay with it.

**Comment by jouni** [comment]
One more thing: this is targeting the Polymer hybrid version, right? I’m wondering how this affects #190 (converting to pure Polymer 2)? Not sure if we should postpone this after that work, to avoid duplicating effort there.

**Comment by platosha** [comment]
Merged manually. Thanks!

**Pull request closed without merging**
