### PR TITLE
Add unit tests for missing use cases

### PR DESCRIPTION
**Pull request by manolo**
Connected to #1

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/22)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/adding-files.html, line 69 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/22#-KA9tCKkmYgUDQWyaKP2:-KA9tCKmz9EeQ3zC5DJf:-1596290719) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ce3b56003f80f33a22f7aaf654d6554be5db049d/test/adding-files.html#L69)):*
The click event is dispatched on the input before its value property is assigned, isn’t it?

---

*[test/adding-files.html, line 181 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/22#-KA9tXeAm0Su4QaVE-q9:-KA9tXeBg6q24nqmSVCB:607151070) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ce3b56003f80f33a22f7aaf654d6554be5db049d/test/adding-files.html#L181)):*
excessive

---

*[test/upload.html, line 276 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/22#-KA9uBB4dynA6JIhg6IK:-KA9uBB4dynA6JIhg6IL:591595171) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ce3b56003f80f33a22f7aaf654d6554be5db049d/test/upload.html#L276)):*
Would be more clear to call the var lastFile, perhaps like: `var lastFile = files[files.length - 1];`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/22)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/adding-files.html, line 69 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/22#-KA9tCKkmYgUDQWyaKP2:-KAA4HAl4F67jW5CcB8H:1899792760) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ce3b56003f80f33a22f7aaf654d6554be5db049d/test/adding-files.html#L69)):*
I don't know if I understand your questiong, but value is set each time the user picks up any file, so the problem is that the second time the popup opens, the value is set, and if the user select the same file there is no change event. 
The solution is clear the value just before opening the input.
The test sets the input value before, then clicks and checks that value was reseted

---

*[test/adding-files.html, line 181 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/22#-KA9tXeAm0Su4QaVE-q9:-KAA4wx9RNugzyzJ2hfZ:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ce3b56003f80f33a22f7aaf654d6554be5db049d/test/adding-files.html#L181)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/22)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/upload.html, line 276 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/22#-KA9uBB4dynA6JIhg6IK:-KAA5QEG5az7VE6MHKEt:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ce3b56003f80f33a22f7aaf654d6554be5db049d/test/upload.html#L276)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/22)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/22)*

**Pull request merged**
