### PR TITLE
Adding first test for basic upload functionality

### PR DESCRIPTION
**Pull request by manolo**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/5)

### CODE REVIEW

**Comment by platosha** [comment]
let us make it cleaner a bit

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/common.html, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XNsUlBU8xqfnEbB93:-K9XNsUlBU8xqfnEbB94:192653299) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/test/common.html#L1)):*
Empty line?

---

*[test/common.js, line 25 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XOFEFcgSlVEXcIN6W:-K9XOFEFcgSlVEXcIN6X:793740969) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/test/common.js#L25)):*
I suppose `getItemArray` is not that useful with upload. Should we remove it?

---

*[test/js/mock-xhr.js, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XQa4seWI_foccscSU:-K9XQa4seWI_foccscSV:-531760708) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/test/js/mock-xhr.js#L1)):*
Can't we just add “philikon/MockHttpRequest” to devDependencies in bower?

---

*[test/upload.html, line 38 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XQxd9SaI1dzkcOgqi:-K9XQxd9SaI1dzkcOgqj:-55000112) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/test/upload.html#L38)):*
Probably this “console.log” is to be removed

---

*[vaadin-upload.html, line 29 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XRNfi9Ma9tKmdzP-B:-K9XRNfi9Ma9tKmdzP-C:2132917075) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/vaadin-upload.html#L29)):*
Why is this div there?

---

*[vaadin-upload.html, line 70 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XRiKIyq-_yliUZADs:-K9XRiKIyq-_yliUZADt:-1538092496) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/vaadin-upload.html#L70)):*
Consider to send file object as event data here, to make it and its xhr accessible for outside work.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-:-K9XSKDAYzPkAv2eukwW:-1215239031)*

**Comment by manolo** [comment]
ok

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[test/common.js, line 25 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XOFEFcgSlVEXcIN6W:-K9XZNnlhgGX0AbzTyHY:160424898) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/test/common.js#L25)):*
yes

---

*[test/js/mock-xhr.js, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XQa4seWI_foccscSU:-K9XZTRn_W9ZJO_KpcTW:-1270536528) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/test/js/mock-xhr.js#L1)):*
He has not bower.json so we cannot. I will open a PR, but in the meanwhile we need this in ours

---

*[test/upload.html, line 38 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XQxd9SaI1dzkcOgqi:-K9XZdFgBw1IDElYMvGW:160424898) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/test/upload.html#L38)):*
yes

---

*[vaadin-upload.html, line 29 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XRNfi9Ma9tKmdzP-B:-K9XZeuymvQCs9RN5tTF:1820839867) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/vaadin-upload.html#L29)):*
Yust for testing

---

*[vaadin-upload.html, line 70 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XRiKIyq-_yliUZADs:-K9XZhemRFNhECZaxPg9:678041242) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/vaadin-upload.html#L70)):*
sure

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-:-K9X_4eGPy2Y0dtXsCP9:5174689)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[test/js/mock-xhr.js, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XQa4seWI_foccscSU:-K9X_MfwKHRn2Yx6lsx9:-798946934) ([raw file](https://github.com/vaadin/vaadin-upload/blob/d861c1faeecf06f27e174b901fe446adbabfde7b/test/js/mock-xhr.js#L1)):*
Believe me, it works right now. I've just tried to run `bower i philikon/MockHttpRequest`, and it does its job, though putting out some warnings about missing bower.json.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5)*

**Comment by platosha** [comment]
Reviewed 4 of 7 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-upload.html, line 66 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XlqHl-iDSamEZu79i:-K9XlqHmOwhBkrdK-soG:913570763) ([raw file](https://github.com/vaadin/vaadin-upload/blob/03e682b2e85c46dc253011dcc43f94fc3b3e7c52/vaadin-upload.html#L66)):*
File already has the xhr reference as a property. Not an issue though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5)*

**Comment by platosha** [comment]
Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5)*

**Comment by platosha** [comment]
Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/js/mock-xhr.js, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XQa4seWI_foccscSU:-K9XmXPO1EPPkihIVkKY:331155958) ([raw file](https://github.com/vaadin/vaadin-upload/blob/914aa4f0ed603f9ae36303fbf8e97e1ac3a2d840/test/js/mock-xhr.js#L1)):*
Alright, this was moved to bower.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[test/common.html, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5#-K9XNsUlBU8xqfnEbB93:-K9XmeuquULhzu6JZYmR:-864509007) ([raw file](https://github.com/vaadin/vaadin-upload/blob/914aa4f0ed603f9ae36303fbf8e97e1ac3a2d840/test/common.html#L1)):*
Resolved.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/5)*

**Pull request merged**
