### PR TITLE
Adding online demo for the webcomponents.org site

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/125)

### CODE REVIEW

**Comment by platosha** [comment]
Can we somehow try if it works before merging?

**Comment by manolo** [comment]
Didn't found any information how to debug this.
Based on other working examples I checked out it should work.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/125#-:-KU1W29dMrU6ioSHwJEP:b-n1pys8)*

**Comment by manolo** [comment]
Obviously the code works if you copy and paste in an html file

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/125#-:-KU1WT6XfyH86YQZFgd9:bv92muj)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 53 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/125#-KU1YnHXe9Nzj5VeA0rj:-KU1YnHYG3-7U1qSOUWc:b-jgt2n6) ([raw file](https://github.com/vaadin/vaadin-upload/blob/7b41df913a4ca528accedbbcac99fab6a5e101a8/README.md#L53)):*
> ```Markdown
> -->
> ```html
> <vaadin-upload accept=".pdf">
> ```

I feel like we should either drop the `accept=".pdf"` limitation, or mention it in the drop label text.

Probably the first way works better for live demos, allowing users to easily drop anything to try.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/125#-:-KU1Y9tJjlqtME8aLwLj:bnfp4nl)*

**Comment by Saulis** [comment]
This should work for a preview: https://beta.webcomponents.org/preview/vaadin/vaadin-upload/7b41df913a4ca528accedbbcac99fab6a5e101a8?editing

**Comment by manolo** [comment]
I didn't see the preview app. Thanks

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 53 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/125#-KU1YnHXe9Nzj5VeA0rj:-KU1eUJRXHoap4Wrbnn0:btosjjb) ([raw file](https://github.com/vaadin/vaadin-upload/blob/7b41df913a4ca528accedbbcac99fab6a5e101a8/README.md#L53)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary>
> I feel like we should either drop the `accept=".pdf"` limitation, or mention it in the drop label text.
> 
> Probably the first way works better for live demos, allowing users to easily drop anything to try.
</details>
Modified the label. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/125#-:-KU1eXzmfxnBINLj7Fae:beuiym8)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/125)*

**Pull request merged**
