### PR TITLE
Add styles for disabled upload button

### PR DESCRIPTION
**Pull request by platosha**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/82)

### CODE REVIEW

**Comment by tehapo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82#-:-KDTdo30WnAn2twehOWJ:1417088721)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[docs/vaadin-upload-custom.adoc, line 64 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82#-KDTfhxuJif-66d-zZVt:-KDTfhxuJif-66d-zZVu:-1262901975) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fd55d1c39604a928f0102ad22ccc66775ba8b8d1/docs/vaadin-upload-custom.adoc#L64)):*
I guess this is incorrect syntax, you have to write 
[propertyname]#maxFiles# 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-upload-custom.adoc, line 64 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82#-KDTfhxuJif-66d-zZVt:-KDTgmPGTXE4FBNlSXQ_:-520416886) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fd55d1c39604a928f0102ad22ccc66775ba8b8d1/docs/vaadin-upload-custom.adoc#L64)):*
I assume that is correct syntax. The browser Asciidoctor preview plugin renders just it fine with `<code class="propertyname">maxFiles</code>`.

The writers guide says: “Any quoted text can be prefixed with an attribute list. The first positional attribute is treated as a role.”, and also lists backquotes among other ways to make quoted text above. http://asciidoctor.org/docs/asciidoc-writers-guide/

@magi42 do you have an opinion regarding using syntax like this: ``` [propertyname]`somePropertyName` ```?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82)*

**Comment by manolo** [comment]
So LGTM. Let's see maggi's opinion.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82#-:-KDTjdlvijPL5uIXmY-N:1411122038)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82)*

**Comment by magi42** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-upload-custom.adoc, line 64 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82#-KDTfhxuJif-66d-zZVt:-KDTlNbS_en_iNeXnHtm:-156057502) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fd55d1c39604a928f0102ad22ccc66775ba8b8d1/docs/vaadin-upload-custom.adoc#L64)):*
Interesting question. The `#...#` notation renders to a `<span>` element, while `` `...` `` renders to `<code>`, and both allow specifying the style name. It's maybe nice that the plug-in has some some styling for the latter, but it is not terribly relevant, as the plug-in doesn't apply the stylesheet. (I nowadays rather recommend only using the Jekyll site preview rather than any other method.) In the stylesheet, both `<code>`and `propertyname` are currently styled the same, but it's perhaps possible that they would not be.

Since we've been using `#...#` in all other cases, it's maybe better to stick to that just for the sake of convention.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82)*

**Comment by platosha** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-upload-custom.adoc, line 64 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82#-KDTfhxuJif-66d-zZVt:-KDTq8l5z3EGBgFNt7Cq:-988199282) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fd55d1c39604a928f0102ad22ccc66775ba8b8d1/docs/vaadin-upload-custom.adoc#L64)):*
Done.

IMO, `<code>` tags in rendering are good to have. It’s semantically better.

The plugin stylesheet is not relevant indeed. But the monospace font for `<code>` is a feature of browsers' default stylesheet, by standard.

I suggest to change all property-/method-/class-name mentions to use ``` `codename` ``` syntax at some point.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-upload-custom.adoc, line 64 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82#-KDTfhxuJif-66d-zZVt:-KDTwFQvdnMVyYLYrdUv:-1625494684) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fd55d1c39604a928f0102ad22ccc66775ba8b8d1/docs/vaadin-upload-custom.adoc#L64)):*
I think you can use the syntax [...]#`foo`# if you want to emphasise  the code.
I don't think this is a big problem, but agree with maggi about maintain coherence with all our doc and use #..# 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-upload-custom.adoc, line 64 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82#-KDTfhxuJif-66d-zZVt:-KDTwzgB2a2IKYpwmykg:-1841404504) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fd55d1c39604a928f0102ad22ccc66775ba8b8d1/docs/vaadin-upload-custom.adoc#L64)):*
 my foo inside # below is wrapped with backticks, reviewable remove then

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82)*

**Comment by magi42** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/vaadin-upload-custom.adoc, line 64 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82#-KDTfhxuJif-66d-zZVt:-KDTvwxwxXVMqk7J5zyy:1237522639) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fd55d1c39604a928f0102ad22ccc66775ba8b8d1/docs/vaadin-upload-custom.adoc#L64)):*
All of those are indeed code elements, so in the pure HTML semantic sense it's true. Well, HTML isn't even supposed to have semantic elements as such... Nevertheless, it's more a question of what is more suitable for source code. It would also be a rather huge change in the convention, so I would rather not do it if the benefit is not remarkable. It's a bit simpler rule to always use `#...#` for any style and at least in Finnish keyboard `` ` `` requires using a dead key to type, so I dislike typing them. On the other hand, `` `...` `` is used in many other places for the same purpose (which also makes it hard to comment such notation in Reviewable and Gerrit). Have to think about it, so maybe at some point, but let's stick to `#` for now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82)*

**Comment by tehapo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/82)*

**Pull request merged**
