### PR TITLE
Demos of MVP Features

### PR DESCRIPTION
**Pull request by platosha**
Connected to #1 

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/27)

### CODE REVIEW

**Comment by manolo** [comment]
This patch changes the way of rendering examples abandoning our custom element in favour of polymer ones. 
This has not been tested in vaadin docsite.
Question @jounik & magi42 : should we merge this in alpha1 or  wait until it's tested in docsite? 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/27#-:-KAC2WxP6KIUu6NXdxiX:307235905)*

**Comment by jounik** [comment]
No live examples in the documentation anymore. For demos, yes, we should stop using our own element in favor of the Polymer one.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/27#-:-KAC6UkY3-4aAkLN9ZLk:1559535448)*

**Comment by manolo** [comment]
Nice, 

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demo/common.html, line 37 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/27#-KAC5IPYpHilU3n1ysAu:-KAC5IPZl-2GlvZ1TczJ:-1817574459) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9dc0e1d623c1db066b08305d9e08aead289a035e/demo/common.html#L37)):*
This stuff is mandatory in the vaadin docsite, otherwise polymer elements are loaded in non elements pages.

---

*[demo/index.html, line 112 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/27#-KAC4ScTzQL1V0ELvvv3:-KAC4ScUWqsvS5vKwwp0:157265231) ([raw file](https://github.com/vaadin/vaadin-upload/blob/69b5998ccbb76a4efebf76e053d7cd9bd0aabf43/demo/index.html#L112)):*
window alert looks very old-fashioned for a component like this. I would use toast, dialog, or a custom div in the component

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/27#-:-KAEKzVDOdCBkUrGy1ut:1986765558)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demo/common.html, line 37 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/27#-KAC5IPYpHilU3n1ysAu:-KAELDBl-SEJoZ9nX52M:747523438) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9dc0e1d623c1db066b08305d9e08aead289a035e/demo/common.html#L37)):*
Don't bother about this, docsite will host screenshots.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/27)*

**Comment by platosha** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/index.html, line 112 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/27#-KAC4ScTzQL1V0ELvvv3:-KAEVh-vAvvvreTgHr-y:-116224978) ([raw file](https://github.com/vaadin/vaadin-upload/blob/69b5998ccbb76a4efebf76e053d7cd9bd0aabf43/demo/index.html#L112)):*
Done, changed to toast. Showing a toast on error is a good pattern to demonstrate here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/27)*

**Pull request merged**
