### PR TITLE
Remove iron-icons dependency

### PR DESCRIPTION
**Pull request by robrez**
Fixes issue #111

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/117)

### CODE REVIEW

**Comment by Saulis** [comment]
Thanks a bunch! Please take a look at the changes I proposed and we'll be happy to merge this patch!

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[bower.json, line 47 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-KNk44o2sz7ssKAcEMCr:-KNk44o2sz7ssKAcEMCs:-254364595) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f57907cddfd2bbd08ff55ed40f14c74ded669cd8/bower.json#L47)):*
> ```JSON
>     "paper-progress": "PolymerElements/paper-progress#^1.0.0",
>     "paper-icon-button": "PolymerElements/paper-icon-button#^1.0.0",
>     "iron-icon": "PolymerElements/iron-icon#^1.0.0"
> ```

Please add `iron-iconset-svg` as a dependency

---

*[vaadin-upload-icons.html, line 22 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-KNk4DPzVCBKX1rweBam:-KNk4DPzVCBKX1rweBan:-1677399914) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f57907cddfd2bbd08ff55ed40f14c74ded669cd8/vaadin-upload-icons.html#L22)):*
> ```HTML
> @pseudoElement vaadin-upload-icons
> -->
> <link rel="import" href="../iron-icon/iron-icon.html">
> ```

Not sure if `iron-icon` needs to be imported here?

---

*[vaadin-upload-icons.html, line 24 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-KNk4INeUSQUYRS7CDkQ:-KNk4INeUSQUYRS7CDkR:329732728) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f57907cddfd2bbd08ff55ed40f14c74ded669cd8/vaadin-upload-icons.html#L24)):*
> ```HTML
> <link rel="import" href="../iron-icon/iron-icon.html">
> <link rel="import" href="../iron-iconset-svg/iron-iconset-svg.html">
> <iron-iconset-svg name="vu-icons" size="24">
> ```

iconset name should be just `vaadin`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-:-KNk4QUKatHOQWyv6c1n:1600530400)*

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-upload-icons.html, line 18 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-KNks3mwxy9MGpk9A_rz:-KNks3mwxy9MGpk9A_s-:1126442842) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f57907cddfd2bbd08ff55ed40f14c74ded669cd8/vaadin-upload-icons.html#L18)):*
> ```HTML
>

**Comment by robrez** [comment]
I pushed changes per your suggestions. I think the way I squashed the commits screwed up your commentary... sorry about that!

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[bower.json, line 47 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-KNk44o2sz7ssKAcEMCr:-KNlfJSk4E-jG_tSfq6l:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f57907cddfd2bbd08ff55ed40f14c74ded669cd8/bower.json#L47)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Please add `iron-iconset-svg` as a dependency
</details>
Done.

---

*[vaadin-upload-icons.html, line 18 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-KNks3mwxy9MGpk9A_rz:-KNlf_xo1RzDogwwy9MP:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f57907cddfd2bbd08ff55ed40f14c74ded669cd8/vaadin-upload-icons.html#L18)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> You can remove `<` since this isn't an actual element.
</details>
Done.

---

*[vaadin-upload-icons.html, line 20 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-KNkrxiGTfq8aYpgJvDv:-KNlfTqQMjCp6O6kj331:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f57907cddfd2bbd08ff55ed40f14c74ded669cd8/vaadin-upload-icons.html#L20)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Let's remove `@pseudoElement` to prevent this popping up in the API docs since it doesn't have any APIs.
</details>
Done.

---

*[vaadin-upload-icons.html, line 22 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-KNk4DPzVCBKX1rweBam:-KNlfavolOmaCcwnFyJi:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f57907cddfd2bbd08ff55ed40f14c74ded669cd8/vaadin-upload-icons.html#L22)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Not sure if `iron-icon` needs to be imported here?
</details>
Done.

---

*[vaadin-upload-icons.html, line 24 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-KNk4INeUSQUYRS7CDkQ:-KNlfdkS47hxV5tD0Gvq:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f57907cddfd2bbd08ff55ed40f14c74ded669cd8/vaadin-upload-icons.html#L24)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Scratch that, let's call it `vaadin-upload` to be explicit.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-:-KNlfjP-FWGV8S1lFOcG:425261626)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-:-KNm2aB9Tdaa978o_7oy:1417088721)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/117#-:-KNpK5IFU-FCPsizzEDA:1417088721)*

**Pull request merged**
