### PR TITLE
Polish Lumo theme

### PR DESCRIPTION
**Pull request by platosha**
Connected to #237

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/244)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/vaadin-upload.html, line 348 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244#-L3hFKjGxR5VmBJtF4oD:-L3hFKjGxR5VmBJtF4oE:bm5deo9) ([raw file](https://github.com/vaadin/vaadin-upload/blob/4fa920db1de642c1f72fa54093ef0d5902923ef7/src/vaadin-upload.html#L348)):*
> ```HTML
>                   addFiles: {
>                     one: 'Select File...',
>                     many: 'Upload Files...'
> ```

BTW the second word is not capitalised in mockup: "Upload files..."
Not a blocker.

---

*[src/vaadin-upload.html, line 652 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244#-L3hFwOIOFBQA7Agy5yg:-L3hFwOIOFBQA7Agy5yh:b-at5pt3) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a7486d608fe94c684abda798c1777ebfb2f304de/src/vaadin-upload.html#L652)):*
> ```HTML
>           );
>           if (evt) {
>             Polymer.Async.microTask.run(this._uploadFile.bind(this, file));
> ```

if this line is no longer needed, consider also removing import for `utils/async.html`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244)*

**Comment by YuriyVaadin** [comment]
One test failing on iphone.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244#-:-L3hHKo_8c1sVz1Jiayc:bgdcfyr)*

**Comment by jouni** [comment]
*[src/vaadin-upload.html, line 348 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244#-L3hFKjGxR5VmBJtF4oD:-L3hJHRDKx-PE6ufrlE1:bgxbfze) ([raw file](https://github.com/vaadin/vaadin-upload/blob/4fa920db1de642c1f72fa54093ef0d5902923ef7/src/vaadin-upload.html#L348)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW the second word is not capitalised in mockup: "Upload files..."
Not a blocker.
</blockquote></details>

Yeah, I struggled with this. Capital “Files” looks somehow better (as button labels are often written in title case), but it’s inconsistent with the drop label. I’m okay with both, to be honest, and maybe it’s good to keep the existing format.

The reason to swap the ellipsis is that the “Upload Files…” button is just the first step in that process, it doesn’t start the uploading yet before you actually select the files from the dialog. Ellipsis is commonly used for these kinds of actions that don’t immediately complete the action ​but only initiate it. On the other hand, dropping files on the drop zone starts the upload immediately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244)*

**Comment by jouni** [comment]
:lgtm: (visually)

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244#-:-L3hLDMycmKPi2Wj6R_e:bnt5qir)*

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244#-L3hTmyjj2UKzQZupbfL:-L3hTmyjj2UKzQZupbfM:bpmeioq) (no related file):*
The text oveflow issues shown in the following image are still there:
screenshot 2018-01-23 11 12 07

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244)*

**Comment by platosha** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244#-L3hTmyjj2UKzQZupbfL:-L3hZnUm_Ex02uePyef8:b-896fix) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The text oveflow issues shown in the following image are still there:
screenshot 2018-01-23 11 12 07
</blockquote></details>

Done.

---

*[src/vaadin-upload.html, line 652 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244#-L3hFwOIOFBQA7Agy5yg:-L3h_5EbuGsE_cBMwNL9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a7486d608fe94c684abda798c1777ebfb2f304de/src/vaadin-upload.html#L652)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

if this line is no longer needed, consider also removing import for `utils/async.html`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244#-:-L3h_uK0EgtTTAbHYrEH:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244#-:-L3hdX1TdK1_dnzEIUMK:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244)*

**Comment by jouni** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/244)*

**Pull request merged**
