### PR TITLE
New: All Uploads Complete event

### PR DESCRIPTION
**Pull request by stramel**
Addresses #67 

Initial approach at it. I will add tests once you guys are good with the approach.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/169)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-upload.html, line 457 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/169#-Ki9YwK_CKfCxxOvXCBR:-Ki9YwKa6B7yGO835s9N:b-5ye2z6) ([raw file](https://github.com/vaadin/vaadin-upload/blob/dfbbc02558be6da6a3caf5f42ca543b11a8f38ca/vaadin-upload.html#L457)):*
> ```HTML
>       'file-abort': '_onFileAbort',
>       'file-remove': '_onFileRemove',
>       'upload-succes': '_onUploadSuccess',
> ```

typo upload-success

---

*[vaadin-upload.html, line 462 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/169#-Ki9njkPRlFhZWrHBAxy:-Ki9njkPRlFhZWrHBAxz:b-o4vvpa) ([raw file](https://github.com/vaadin/vaadin-upload/blob/dfbbc02558be6da6a3caf5f42ca543b11a8f38ca/vaadin-upload.html#L462)):*
> ```HTML
>     _onUploadSuccess: function() {
>       var status = this.files.reduce(function(files, file) {
>         if (!file.held) {
> ```

I'm a bit agnostic about notifying when files are held, to me uploads-complete means that all files were uploaded.
If auto is not set, it should be the user responsibility to fire it, or retry it in case some file failed. 
For the App perspective, it should be only interested on doing some action when everything was uploaded.
I don't think we should pass info in the event detail, since the developer has access to the file array
For any use-case, the developer can listen to upload-success and implement his own algorithm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/169)*

**Comment by stramel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-upload.html, line 457 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/169#-Ki9YwK_CKfCxxOvXCBR:-KiG86i4xKTSFiBFlgwl:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/dfbbc02558be6da6a3caf5f42ca543b11a8f38ca/vaadin-upload.html#L457)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

typo upload-success
</blockquote></details>

Done.

---

*[vaadin-upload.html, line 462 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/169#-Ki9njkPRlFhZWrHBAxy:-KiG8J8006UJoNlxC2Ee:b5k4vrm) ([raw file](https://github.com/vaadin/vaadin-upload/blob/dfbbc02558be6da6a3caf5f42ca543b11a8f38ca/vaadin-upload.html#L462)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I'm a bit agnostic about notifying when files are held, to me uploads-complete means that all files were uploaded.
If auto is not set, it should be the user responsibility to fire it, or retry it in case some file failed. 
For the App perspective, it should be only interested on doing some action when everything was uploaded.
I don't think we should pass info in the event detail, since the developer has access to the file array
For any use-case, the developer can listen to upload-success and implement his own algorithm
</blockquote></details>

Hmmm, I could see this going a bunch of different ways:

- All files were uploaded, meaning this won't fire if there were held files using `no-auto` and manual triggering.
- All batched files were uploaded, meaning this will fire if all files were uploaded or a subset using `no-auto` and manual triggering.
- All files were successfully uploaded, meaning this won't fire if there were held files using `no-auto` and manual triggering OR if there were not any that failed.
- All batched files were successfully uploaded, meaning this will fire if all files were uploaded or a subset using `no-auto` and manual triggering OR if there were not any that failed.

Currently, thinking about this a bit more, I believe this event will not fire if there is an ending failure thus meaning that option 4 with a bug. I can implement whichever option above you feel is a good direction. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/169)*

**Comment by stramel** [comment]
Ping @manolo @saulis

**Comment by limonte** [comment]
ping @manolo @Saulis

**Comment by Saulis** [comment]
My only question is if aborted / errored files should be or not be taken into account as completed files? Otherwise, looks good to me after tests are added.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/169#-:-KjNhZnoSQroVw43LGLt:bjwbdxx)*

**Comment by stramel** [comment]
@saulis if you take a look at the root issue #67 @platosha brings up the use of Promises. Not sure which direction you guys are wanting me to go

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-upload.html, line 462 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/169#-Ki9njkPRlFhZWrHBAxy:-KkZeJvsbNOllyhrZQSw:b-7ws4h2) ([raw file](https://github.com/vaadin/vaadin-upload/blob/dfbbc02558be6da6a3caf5f42ca543b11a8f38ca/vaadin-upload.html#L462)):*
<details><summary><i>Previously, stramel (Michael Stramel) wrote…</i></summary><blockquote>

Hmmm, I could see this going a bunch of different ways:

- All files were uploaded, meaning this won't fire if there were held files using `no-auto` and manual triggering.
- All batched files were uploaded, meaning this will fire if all files were uploaded or a subset using `no-auto` and manual triggering.
- All files were successfully uploaded, meaning this won't fire if there were held files using `no-auto` and manual triggering OR if there were not any that failed.
- All batched files were successfully uploaded, meaning this will fire if all files were uploaded or a subset using `no-auto` and manual triggering OR if there were not any that failed.

Currently, thinking about this a bit more, I believe this event will not fire if there is an ending failure thus meaning that option 4 with a bug. I can implement whichever option above you feel is a good direction. 
</blockquote></details>

I think the 3rd option is the most meaningful. `uploads-complete` means that all files in the queue were uploaded correctly. For the case when all uploads were complete, but there was some of them with errors we might have a second event `uploads-error`. I need to confirm with the team tough. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/169)*

**Comment by stramel** [comment]
@platosha @manolo should we focus on the refactor? I have outstanding changes on this and some clarification from you guys on the direction we would want to take.

**Comment by manolo** [comment]
this should be rebased after last changes in master. @stramel  can you do?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/169#-:-KwE6j51p0zrzN9oN49W:b-wgp1wa)*

**Pull request closed without merging**
