### PR TITLE
Upload Mode with option RAW added.

### PR DESCRIPTION
**Pull request by Bulan**
Send file to server without wrapping in FormData.

Fixes issue https://github.com/vaadin/vaadin-upload/issues/96

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/97)

### CODE REVIEW

**Comment by Saulis** [comment]
:lgtm: Any comments @platosha or @manolo ?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/97#-:-KGB5U6oeyalSkX0Le3c:-377586601)*

**Comment by platosha** [comment]
Thanks for your PR, @Bulan. Unfortunately, it lacks tests, asciidoc documentation and examples, so it cannot be merged right away.

Generally, introducing a separate mode with its property for the reason of #96 is redundant for now, I think.

Instead, I would restructure the `_uploadFile` method to make `preventDefault()` for `'upload-request'` event work a bit differently: to skip the default `xhr.send`, but without skipping the rest of the upload status handling work in the `_uploadFile`. So that in the `'upload-request'` event handler the users could prevent the default `xhr.send(formData)` and make their own `xhr.send(file)`, for example.

This should be enough to solve the #96 with a simple event handler, without any API changes in the upload like introducing a new property. To proceed with this, let me prepare another PR with my suggestions implemented in the next few days.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/97#-:-KGB5nE8RWMcQ-y9w0MS:354421647)*

**Comment by Bulan** [comment]
Any update on the progress on this @platosha ?

**Comment by platosha** [comment]
@Bulan sorry for a long delay. See #113 for my proposal.

**Comment by tomivirkki** [comment]
I assume this can be closed since #113 is already merged, correct me if I'm wrong

**Pull request closed without merging**
