### PR TITLE
Support for light dom content in Angular 2

### LINKED ISSUE #98: Light DOM content is not handled reliably when using shady DOM in Angular 2

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #98 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/99)

### CODE REVIEW

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[directives/vaadin-upload.ts, line 67 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99#-KGGeO05w09cl3spEpp5:-KGGeO05w09cl3spEpp6:520649978) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6f2fe27b4c785dd9048729fea557526578d5f4c8/directives/vaadin-upload.ts#L67)):*
Not a blocker, just as a suggestion.

I would call them `addedKey` and `removableKey`. They are string keys, not just random identifiers / digits.

---

*[directives/vaadin-upload.ts, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99#-KGGdQjpYxvqVRxdM9-T:-KGGdQjpYxvqVRxdM9-U:-460757402) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6f2fe27b4c785dd9048729fea557526578d5f4c8/directives/vaadin-upload.ts#L72)):*
May be write `lightDom.appendChild(child);` here for consistency?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99)*

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[directives/vaadin-upload.ts, line 67 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99#-KGGeO05w09cl3spEpp5:-KGGiP8GgX2_RofBguyW:-1068175612) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6f2fe27b4c785dd9048729fea557526578d5f4c8/directives/vaadin-upload.ts#L67)):*
Removed the ids

---

*[directives/vaadin-upload.ts, line 72 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99#-KGGdQjpYxvqVRxdM9-T:-KGGiRZpwEZTbSNHvE7d:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6f2fe27b4c785dd9048729fea557526578d5f4c8/directives/vaadin-upload.ts#L72)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[directives/vaadin-upload.ts, line 104 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99#-KGGl1KeMsGBW5DHsYOK:-KGGl1KeMsGBW5DHsYOL:167967599) ([raw file](https://github.com/vaadin/vaadin-upload/blob/e55532047e029d896503da4232495c3661a7a652/directives/vaadin-upload.ts#L104)):*
Redundant empty line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99)*

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[directives/vaadin-upload.ts, line 104 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99#-KGGl1KeMsGBW5DHsYOK:-KGH1EevPn7nII9R_REc:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/e55532047e029d896503da4232495c3661a7a652/directives/vaadin-upload.ts#L104)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99)*

**Comment by platosha** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99#-:-KGH85Aho7N5XpmLltPe:980077423)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[directives/vaadin-upload.ts, line 102 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99#-KGHEE8RtV96anlURSKn:-KGHEE8S97MhZwhAwjGE:-355755090) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5df7fdbf9ac4a06f4decaba5886663432544ae04/directives/vaadin-upload.ts#L102)):*
Q: `!node.tagName` is here to apply for `#text` etc nodes? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99)*

**Comment by tomivirkki** [comment]
*[directives/vaadin-upload.ts, line 102 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99#-KGHEE8RtV96anlURSKn:-KGHEqCEI6XGBuQB55Ux:-34731404) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5df7fdbf9ac4a06f4decaba5886663432544ae04/directives/vaadin-upload.ts#L102)):*
That's right

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/99)*

**Pull request merged**
