### PR TITLE
Disallow opening file dialog when max files reached

### PR DESCRIPTION
**Pull request by tomivirkki**
Connects to #196

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/197)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 816 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/197#-Km1SO3U_40AHkhoaMF0:-Km1SO3U_40AHkhoaMF1:bsvzczu) ([raw file](https://github.com/vaadin/vaadin-upload/blob/482d582666339cf8b60948b774c088ea71a5e28a/vaadin-upload.html#L816)):*
> ······

trailing spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/197#-:-Km1SdMqPlS9WBZZuWMm:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/197#-:-Km1SlL2CIxqP0uSNYoO:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-upload.html, line 816 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/197#-Km1SO3U_40AHkhoaMF0:-Km1TeXvN9UXKJUrdr9j:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/482d582666339cf8b60948b774c088ea71a5e28a/vaadin-upload.html#L816)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> ······

trailing spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/197)*

**Comment by limonte** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/197)*

**Pull request merged**
