### PR TITLE
New: Allow Re-upload

### PR DESCRIPTION
**Pull request by stramel**
Allows for re-uploading files. This is a follow-up for #149 

**TODO:**

- [x] Tests

---

@Saulis How do you want to handle these scenarios:

- adding more than `maxFiles` at once
- display of file list

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/175)

### CODE REVIEW

**Comment by stramel** [comment]
Ping @saulis manolo

**Comment by Saulis** [comment]
@stramel hmm the way I was thinking about this was that the existing functionality would be pretty much unmodified, but when `allowReupload` is `true`, adding/dropping files would always be enabled and when new files are being added, the previous ones are always cleared from the list. 

Does that make sense? In my understanding, the behavior related with max files should be unchanged.

**Comment by platosha** [comment]
@Saulis do you mean replacing all the files when adding new ones, or just those which file names already exist in the list?

The first way would require users that re-upload multiple files to drop/pick them all at once. I doubt that it is a good UX.

**Comment by stramel** [comment]
Ping @Saulis, can you follow up? Thanks! :)

**Comment by Saulis** [comment]
Ah, sorry for the delay.

To answer Anton's question: I was thinking on requiring the user to pick all the files for uploading with the same go. I understand your concern on possible UX problems, but I don't think it should be a problem in the use cases where this feature is aimed.

I'm OK also with the proposal of overwriting only the files with the same filenames from the list, but I think in most cases reuploading happens with different files.

I'm proposing we go forward with the simplest possible implementation and then add complexity later if we need to improve on the UX for the users of this particular feature.

**Comment by stramel** [comment]
@Saulis So I guess I'm still confused on how we want to handle these situations.

> How do you want to handle these scenarios:
>
> - adding more than maxFiles at once
> - display of file list

**Comment by Saulis** [comment]
> adding more than maxFiles at once
I'd say that this should work like it does now: only the allowed number of files will be added and then an error is displayed stating that the number is exceeded. Only exception would be that the upload button would still be enabled after max files is reached.

> display of file list
Did you have some changes to the list in mind? I was thinking it should look just like it normally does.

**Comment by stramel** [comment]
@saulis

> display of file list
> Did you have some changes to the list in mind? I was thinking it should look just like it normally does.

Do I keep a list of all files that are uploaded or do I do a kinda fifo kinda list?

**Comment by Saulis** [comment]
> Do I keep a list of all files that are uploaded or do I do a kinda fifo kinda list?

When reupload is enabled, I would consider just clearing the list when new items are selected for uploading.

**Comment by stramel** [comment]
Okay :+1: will try to get back to this soon

**Comment by stramel** [comment]
@Saulis I have it clearing the files array on the addition of files. However, I think this is going to be very poor behavior for queuing files. But I'm not sure how to handle that because it gets pretty complex. Did a pretty basic FIFO setup for it but that didn't feel right either. 

Let me know what you think.

**Comment by stramel** [comment]
@platosha @manolo Are you guys willing to take a look at this or should we focus on the refactor?

**Comment by manolo** [comment]
Hi @stramel master has changed a lot since we have merged the pure polymer-2 branch. Do you mind to rebase this PR and sorry for the inconveniences? 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/175#-:-KwE6SWIzQf7dLrxOq4b:bu58xzh)*

**Comment by stramel** [comment]
I think I may close this one and opt for the refactor here. I can re-open if you believe it would be useful now

**Pull request closed without merging**
