### PR TITLE
Remove file-add and file-remove events.

### PR DESCRIPTION
**Pull request by manolo**
Connected to #39 
Connected to #40

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/50)

### CODE REVIEW

**Comment by samiheikki** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 101 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KCy8Hy8yRzfT-_W0loZ:-KCy8Hy8yRzfT-_W0lo_:-146841290) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6b0b141151ac3fbd92e1432319de2cc872d65078/demo/advanced.html#L101)):*
Not sure how this should work. I'm getting `Uncaught ReferenceError: is is not defined`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 101 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KCy8Hy8yRzfT-_W0loZ:-KCyJYMcK68rLaizbxok:485310725) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6b0b141151ac3fbd92e1432319de2cc872d65078/demo/advanced.html#L101)):*
That was a wrong refactoring 'is' should read 'indexSplices'

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Comment by manolo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/advanced.html, line 101 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KCy8Hy8yRzfT-_W0loZ:-KCyK_2iAbAhpgERscXP:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6b0b141151ac3fbd92e1432319de2cc872d65078/demo/advanced.html#L101)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Comment by tehapo** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/advanced.html, line 84 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KCykAo93v0H8XiORuA1:-KCykAo93v0H8XiORuA2:-429814258) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2586f6a3ea428798acae4dc52beaaa48c4d69450/demo/advanced.html#L84)):*
Using the `for..in` construct to iterate though an array is generally a bit dangerous and error-prone. I would change all of those into "normal" `for` loops. I know this is only demo code, but maybe still. :relaxed:  

http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-such-a-bad-idea

---

*[demo/advanced.html, line 85 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KCykljddeOeb9iS37at:-KCykljeGJbwCgrDfhg0:-421537469) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2586f6a3ea428798acae4dc52beaaa48c4d69450/demo/advanced.html#L85)):*
Extra space between "=" and "value[i]".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demo/advanced.html, line 84 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KCykAo93v0H8XiORuA1:-KCzN5EpSPb43gfzWOMm:-330629207) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2586f6a3ea428798acae4dc52beaaa48c4d69450/demo/advanced.html#L84)):*
Well, this PR aim is to discuss about the convenience of removing the events, and the code the developer has to write if we remove it. I'll change the `for` if we decide continue, but it even makes bigger the code the user has to write.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demo/advanced.html, line 84 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KCykAo93v0H8XiORuA1:-KCzXufsdgvqidnfAqCk:32117934) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2586f6a3ea428798acae4dc52beaaa48c4d69450/demo/advanced.html#L84)):*
Sure, you're right. Now that I had the chance to think about this in more detail, I would suggest that we do remove the `file-add` and `file-remove` events. We can add those later if needed.

For this complex event handler code, I would change the example to use data-binding and a `dom-repeat` template to simplify things. That would be clean way to avoid having to deal with the complexity of the `files-changed` event.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Comment by tomivirkki** [comment]
*[demo/advanced.html, line 84 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KCykAo93v0H8XiORuA1:-KCzY0PJ2IwvtQxHkGPw:993632356) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2586f6a3ea428798acae4dc52beaaa48c4d69450/demo/advanced.html#L84)):*
Also, I think any non-Polymer JS developer would rather just re-render the whole list on "files-changed" event (when the array length is changed) instead of trying to figure out the individual changes in the array.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/advanced.html, line 84 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KCykAo93v0H8XiORuA1:-KCztefAVD6wRbStVmKR:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2586f6a3ea428798acae4dc52beaaa48c4d69450/demo/advanced.html#L84)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/advanced.html, line 85 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KCykljddeOeb9iS37at:-KCzthgzCIokGYa8nM9k:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2586f6a3ea428798acae4dc52beaaa48c4d69450/demo/advanced.html#L85)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Comment by manolo** [comment]
IMO, these changes fixes the example, but does not fixes nor show the complexity for non polymer users about how to handle changes in file array. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-:-KCzw1ARbKeUJDBVESNa:228752424)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/advanced.html, line 40 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KD28yZ3ZnYL_UR180tJ:-KD28yZ43kenHPKmFlOr:2005704236) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6afa75a943845105f72d13ec9538fdddf990072f/demo/advanced.html#L40)):*
Awesome that you replaced the eventListeners with data binding!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-:-KD2A44z_xfkcjo-VMPz:1417088721)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/advanced.html, line 40 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50#-KD28yZ3ZnYL_UR180tJ:-KD2N5FM9E_z44enBtve:964027202) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6afa75a943845105f72d13ec9538fdddf990072f/demo/advanced.html#L40)):*
Data binding might not be available in other frameworks, so they need events instead.
Should we document how to handle envents?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Comment by Saulis** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Comment by Saulis** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/50)*

**Pull request merged**
