### PR TITLE
Add attribute for managing name at content-disposition

### PR DESCRIPTION
**Pull request by abezhinaru**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/121)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Hi @abezhinaru 
Thanks for the PR, the change itself looks good to me. Still needs a test case and some documentation about the new feature at /docs. Just ping us if you need help with that.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/121#-:-KQZhTY4AS-6F9uhwXKE:beqw5sg)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 314 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/121#-KQZmlmHbfijKDxwqZX2:-KQZmlmHbfijKDxwqZX3:b65lq8j) ([raw file](https://github.com/vaadin/vaadin-upload/blob/05900fb8b80d712269a6e0e6a4aa35991ff145cd/vaadin-upload.html#L314)):*
> ```HTML
> 
>       /**
>        * Specifies the 'name' property at Content-Disposition
> ```

This description is not clear enough. I would rephrase this to something like:

```
Specifies the 'name' of the field (file) sent to the server.
This is sent as the 'name' property of the 'Content-Disposition' header of the 'multipart/form-data' request for this field.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/121)*

**Comment by platosha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-upload.html, line 316 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/121#-KQZtbP9hDHPpETJi18g:-KQZtbPAoj-DrNEihLJ-:b-r1kaqu) ([raw file](https://github.com/vaadin/vaadin-upload/blob/05900fb8b80d712269a6e0e6a4aa35991ff145cd/vaadin-upload.html#L316)):*
> ```HTML
>        * Specifies the 'name' property at Content-Disposition
>        */
>       formDataFilename: {
> ```

Having `Filename` in the property name could be confusing.

I would simply call it `formDataName`, because it my not relate with the actual filename.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/121)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/121)*

**Pull request closed without merging**
