### PR TITLE
Fixes mixins documentation

### LINKED ISSUE #53: Clarify that the style mixins are not CSS properties
Currently the documentation speaks about CSS properties while it should make it clear that the styling options are mixins. Make sure to fix this in API docs and AsciiDocs.

Polymer elements always clearly state that some custom property is a mixin. Something like "A mixin that is applied to the internal ripple".

See this page for an example:
https://elements.polymer-project.org/elements/paper-dropdown-menu

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #53

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/55)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-upload.html, line 45 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/55#-KCz1AzesmrjKWP5YU5y:-KCz1AzesmrjKWP5YU5z:-463795130) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a00aa827062fd2cb76a124156fb0a57943a1b903/vaadin-upload.html#L45)):*
Not caused by this PR, but overlooked previously.

`--vaadin-upload-file-canceled` mixin concers the file element, and is used inside it. Please move this doc line to the -file.html.

---

*[docs/vaadin-upload-custom.adoc, line 65 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/55#-KCz1aRvWN2nrZ3pgByF:-KCz1aRw_uLAxFm_QNrA:1109189423) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a00aa827062fd2cb76a124156fb0a57943a1b903/docs/vaadin-upload-custom.adoc#L65)):*
This line is also to be moved to the `vaadin-upload-file` element section list below.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/55)*

**Comment by samiheikki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-upload.html, line 45 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/55#-KCz1AzesmrjKWP5YU5y:-KCz56d2WWe7f0yJnV89:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a00aa827062fd2cb76a124156fb0a57943a1b903/vaadin-upload.html#L45)):*
Done.

---

*[docs/vaadin-upload-custom.adoc, line 65 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/55#-KCz1aRvWN2nrZ3pgByF:-KCz53rHH6EuNWp_zWEz:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a00aa827062fd2cb76a124156fb0a57943a1b903/docs/vaadin-upload-custom.adoc#L65)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/55)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/55#-:-KCz69KUvyqP7DdZyHzz:1417088721)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/55)*

**Comment by tomivirkki** [comment]
:lgtm: 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/55#-:-KCz9Aukc2R49fJFZrsi:980077423)*

**Pull request merged**
