### PR TITLE
Fix: Wrap drop label

### LINKED ISSUE #210: dropLabel should wrap on narrow viewports
When `<vaadin-upload>` is narrow, dropLabel should probably wrap and get shown under the button. Right now it gets cut off.

screen shot 2017-09-02 at 10 03 02 am

### PR DESCRIPTION
**Pull request by stramel**
Fixes #210 

Feel free to close if you disagree with this approach. Seemed reasonable to me and was quick so I figured I would throw a PR out.

Not sure the impact this would have on existing users.

**Preview:**
image
image
image

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/211)

### CODE REVIEW

**Comment by stramel** [comment]
Ping @manolo @marcushellberg @platosha @jouni  PTAL

**Comment by manolo** [comment]
@stramel  there are big changes in master related with styling can you apply this patch someway to it. I think this wrap behaviour  makes sense. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/211#-:-KwE6xPvKzeYrHBM0xv-:b-dxn6dv)*

**Comment by stramel** [comment]
@manolo Rebased onto the latest master. Almost not sure these changes are necessary. They can easily be added using the `::part` API

**Comment by stramel** [comment]
Ping @manolo @jouni

**Comment by platosha** [comment]
LGTM

@jouni what do you think?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/211#-:-KxmBRq0pcLSJhlbOly_:b-e91dp9)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/211#-:-KxmCurU2GzPGgPNVSxo:bnfp4nl)*

**Comment by jouni** [comment]
Yeah, LGTM.

**Pull request merged**
