### PR TITLE
Drag Ripple MAX_RADIUS Disabled

### PR DESCRIPTION
**Pull request by platosha**
Connected with #1

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/21)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vaadin-upload.html, line 293 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21#-KA622FxFf1QL_XCW9oM:-KA622FxFf1QL_XCW9oN:-1341853400) ([raw file](https://github.com/vaadin/vaadin-upload/blob/7a20709c61364da171b1d0237e86b7e5e4486e2e/vaadin-upload.html#L293)):*
I get asynchronously in my console : Uncaught TypeError: Cannot redefine property: radius 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-upload.html, line 304 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21#-KA6OjKZV4KtOLUo4Fu8:-KA6OjKZV4KtOLUo4Fu9:-2069917658) ([raw file](https://github.com/vaadin/vaadin-upload/blob/7a20709c61364da171b1d0237e86b7e5e4486e2e/vaadin-upload.html#L304)):*
Thinking a little more about this, I think that  
1. It's a bad idea to patch all the instances, and even patch the same instance multiple times
2. we shouldn't maintain all this code here
3. To me it's less risky if we try to patch the function string finding and replacing the MAX_RADIUS constant.

This code works to me, wdyt?:

```
        var proto = Object.getPrototypeOf(this.$.dragRipple.ripples[0]);
        if (!proto._radius) {
          proto._radius = Object.getOwnPropertyDescriptor(proto, "radius").get;
          var s = proto._radius.toString()
             .replace(/Ripple\.MAX_RADIUS/g, window.innerWidth)
             .replace(/.*{([\s\S]*)}/,'$1');
          Object.defineProperty(proto, 'radius', {get: new Function(s)});
        }
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-upload.html, line 304 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21#-KA6OjKZV4KtOLUo4Fu8:-KA9EKvS3gTDayNWYzRT:-1637630963) ([raw file](https://github.com/vaadin/vaadin-upload/blob/7a20709c61364da171b1d0237e86b7e5e4486e2e/vaadin-upload.html#L304)):*
Shorter code, even:

```
        var proto = Object.getPrototypeOf(this.$.dragRipple.ripples[0]);
        if (!proto._radius) {
          proto._radius = Object.getOwnPropertyDescriptor(proto, 'radius').get;
          var s = proto._radius.toString()
             .replace(/.*{([\s\S]*)}/,'var Ripple={MAX_RADIUS:9999};\n$1');
          Object.defineProperty(proto, 'radius', {get: new Function(s)});
        }
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21)*

**Comment by platosha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-upload.html, line 304 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21#-KA6OjKZV4KtOLUo4Fu8:-KA9W9rW8vfWjGCjbL6C:1001228589) ([raw file](https://github.com/vaadin/vaadin-upload/blob/7a20709c61364da171b1d0237e86b7e5e4486e2e/vaadin-upload.html#L304)):*
Generally, I think patching ripple instances is the lesser evil against patching their prototype, which affects all paper-ripples. But it's true that the implementation could be cleaner. I'll take your approach for it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21)*

**Comment by jounik** [comment]
I dunno… to me this feels like an overkill for this design detail. At least at this stage. Can’t we just make a pull request to the ripple element instead, to have to option to remove the limit?

**Comment by manolo** [comment]
Agree, let's open a ticket to the paper-ripple, and eventually send a patch, and let the hack here with a link to those tickets, and a FIXME: remove this hack after #xxx is fixed

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21#-:-KA9k9vIM93qskmfVRVi:1093497814)*

**Comment by platosha** [comment]
Added FIXME.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 293 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21#-KA622FxFf1QL_XCW9oM:-KAA4JH6jCnSTqlmKF4-:1758359711) ([raw file](https://github.com/vaadin/vaadin-upload/blob/7a20709c61364da171b1d0237e86b7e5e4486e2e/vaadin-upload.html#L293)):*
Fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21#-:-KAA4bHKRHrQboARyvbC:496405062)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/21)*

**Pull request merged**
