### PR TITLE
Clarify usage of the accept attribute

### LINKED ISSUE #89: Document "accept" limitation explicitly
Currently we state in the documentation for the "accept" property that "depending on the browser and system it might not work". It’s really vague for the user, as they might not have any idea what it actually means for them.

We need to clarify the message in the docs that you should avoid using file extension limitations because they do not work in Safari (#56), and that you should use mime-type limitations instead.

### PR DESCRIPTION
**Pull request by manolo**
Fixes #89  #56 #91

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/91)

### CODE REVIEW

**Comment by magi42** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[vaadin-upload.html, line 282 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAx-_P6HWhz02tNDqQ:-KFAx-_QpLT1GHhEUF-x:-732704396) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/vaadin-upload.html#L282)):*
I don't understand what the `mime_type` and `file_extension` are here. They are identifiers, so should it be used, for example: `accept="mime_type,file_extension"` or how?

OK, looking at the example below, should you instead talk about concepts here: "_Syntax: comma-separated list of MIME type patterns (wildcards are allowed) or file extensions. Notice that MIME types are widely supported, while file extensions..._"

---

*[vaadin-upload.html, line 284 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAxvY-1hLhQKItV17I:-KFAxvY0fxEnFFaw0MZ0:1398089199) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/vaadin-upload.html#L284)):*
No example of file extensions.

---

*[demo/index.html, line 108 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAy443O4RKVy13kI3H:-KFAy443O4RKVy13kI3I:402770784) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/demo/index.html#L108)):*
The list looks odd, I don't see what the items in the list are.

---

*[docs/vaadin-upload-basic.adoc, line 31 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAyLseRlsQXq-_mfiO:-KFAyLseRlsQXq-_mfiP:557873946) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/docs/vaadin-upload-basic.adoc#L31)):*
* OK, this clarifies the meaning of the stuff earlier.
* WIthout dash: "MIME types" and "file extensions".
* Are you sure the URL syntax is correct AsciiDoc?

---

*[docs/vaadin-upload-basic.adoc, line 33 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAycpK3wfuB_IKCq91:-KFAycpLo221GsqtQU-D:890347956) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/docs/vaadin-upload-basic.adoc#L33)):*
* without dash: "MIME types"
* The link doesn't really seem be to a "MIME types specification"... Not sure how to make it better.
* Are you sure the URL syntax is correct AsciiDoc?

---

*[docs/vaadin-upload-basic.adoc, line 34 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFB2H-Sop-RVcUBi9o-:-KFB2H-Sop-RVcUBi9o0:-146938257) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/docs/vaadin-upload-basic.adoc#L34)):*
* The URL syntax looks a bit odd, I hope it's valid AsciiDoc.
* I'd make the reference more exact: "`...accept the file extension syntax defined in the https://www.w3.org/TR/html5/forms.html#file-upload-state-%28type=file%29[HTML5 file upload specification].`"

---

*[docs/vaadin-upload-basic.adoc, line 37 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFB4uw5Q430unoigE6I:-KFB4uw6SAcfZxnDe2U9:-579224395) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/docs/vaadin-upload-basic.adoc#L37)):*
The example is not introduced. Typically use: "For example:" or elaborate more "You can use validation parameters as follows:"

---

*[docs/vaadin-upload-basic.adoc, line 40 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFB5PL17LdtGN8pNpFL:-KFB5PL17LdtGN8pNpFM:-838429750) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/docs/vaadin-upload-basic.adoc#L40)):*
The line gets rather long here. These don't go to the print edition, where the limit would be 63 chars, but nevertheless. I myself like to wrap and indent such lines so that the attributes are left-aligned.

```
<vaadin-upload max-files="3"
               accept="application/pdf,image/*"
               max-file-size="1000000">
</vaadin-upload>
```

It's a matter of taste really. It would be sort of nice to use /> there instead of closing tag.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91)*

**Comment by manolo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[vaadin-upload.html, line 282 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAx-_P6HWhz02tNDqQ:-KFD1xjjxlUrb-cdNJg9:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/vaadin-upload.html#L282)):*
Done.

---

*[vaadin-upload.html, line 284 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAxvY-1hLhQKItV17I:-KFD1ySZdiciAraSgzwh:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/vaadin-upload.html#L284)):*
Done.

---

*[demo/index.html, line 108 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAy443O4RKVy13kI3H:-KFD2rW54tRNi2QjmsYv:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/demo/index.html#L108)):*
Done.

---

*[docs/vaadin-upload-basic.adoc, line 31 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAyLseRlsQXq-_mfiO:-KFD7WkfsK1u0JVwGD4K:541192347) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/docs/vaadin-upload-basic.adoc#L31)):*
Fixed URL, and rephrase a little bit

---

*[docs/vaadin-upload-basic.adoc, line 33 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAycpK3wfuB_IKCq91:-KFD4wrKAe55zzDiUk3H:542993360) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/docs/vaadin-upload-basic.adoc#L33)):*
Clarified a little bit and fixed url

---

*[docs/vaadin-upload-basic.adoc, line 34 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFB2H-Sop-RVcUBi9o-:-KFD5NIJcVLY-Gpeg7DO:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/docs/vaadin-upload-basic.adoc#L34)):*
Done.

---

*[docs/vaadin-upload-basic.adoc, line 37 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFB4uw5Q430unoigE6I:-KFD7Cdb_GmRuzBhgOv3:-1518632590) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/docs/vaadin-upload-basic.adoc#L37)):*
1.- changed sentence above a little bit
2.-  Added introductory sentence to example

---

*[docs/vaadin-upload-basic.adoc, line 40 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFB5PL17LdtGN8pNpFL:-KFD7T69StKTqCxKMBTK:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/docs/vaadin-upload-basic.adoc#L40)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91)*

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[demo/index.html, line 108 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAy443O4RKVy13kI3H:-KFETURN0tbp9DcqNHmk:-339864522) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/demo/index.html#L108)):*
“... and Size, and using ...” — feels too repetitive here. Also may sound like the event is something that could also be used to restrict accepted files, which is not true.

May be, put it like this: “Restricting File Count, Type and Size”?

The main topic of the example is restricting, the event is a consequence of the restrictions. I think it's safe skip mentioning the event in the title.

---

*[demo/index.html, line 108 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFEST8slMkfKro-SI-e:-KFEST8tbsT9Lu8OBRFN:-654316018) ([raw file](https://github.com/vaadin/vaadin-upload/blob/b15d3301723efe93482d9037121206406eac9a3a/demo/index.html#L108)):*
Mind the Title Case, Please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91)*

**Comment by magi42** [comment]
Reviewed 1 of 1 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[vaadin-upload.html, line 283 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFEXcbZ7IEfsvdLjojs:-KFEXcb_7iegN8l7QwO5:1331333283) ([raw file](https://github.com/vaadin/vaadin-upload/blob/b15d3301723efe93482d9037121206406eac9a3a/vaadin-upload.html#L283)):*
* Oh, "is" -> "are"

---

*[vaadin-upload.html, line 284 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFEXfvrhPwQz5n6ejFF:-KFEXfvrhPwQz5n6ejFG:2036626282) ([raw file](https://github.com/vaadin/vaadin-upload/blob/b15d3301723efe93482d9037121206406eac9a3a/vaadin-upload.html#L284)):*
Same here, is -> are. And also "it" -> "them".

---

*[demo/index.html, line 108 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFEST8slMkfKro-SI-e:-KFEXz4_t0QjiaHtPA6W:-1052891847) ([raw file](https://github.com/vaadin/vaadin-upload/blob/b15d3301723efe93482d9037121206406eac9a3a/demo/index.html#L108)):*
* Article: "Using _the_"
* The title is rather long and complex. Maybe not list all things you can restrict, but something generic such as "Restricting Uploadable Files" or "Making Restrictions on Files to Upload" or something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91)*

**Comment by manolo** [comment]
Review status: 1 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[vaadin-upload.html, line 283 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFEXcbZ7IEfsvdLjojs:-KFIXk476rihPpbGl2PC:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/b15d3301723efe93482d9037121206406eac9a3a/vaadin-upload.html#L283)):*
Done.

---

*[vaadin-upload.html, line 284 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFEXfvrhPwQz5n6ejFF:-KFIXp8BJ5dm48sbBwqi:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/b15d3301723efe93482d9037121206406eac9a3a/vaadin-upload.html#L284)):*
Done.

---

*[demo/index.html, line 108 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFAy443O4RKVy13kI3H:-KFIYE9UuHoHqe_GhLmI:-659976242) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f11b93d388ca34b07d6843380d5c4b9c81b9b3d3/demo/index.html#L108)):*
agree with Magi, changed the title 

---

*[demo/index.html, line 108 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91#-KFEST8slMkfKro-SI-e:-KFIY9gYn3oXiSIWJCMd:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/b15d3301723efe93482d9037121206406eac9a3a/demo/index.html#L108)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91)*

**Comment by magi42** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/91)*

**Pull request merged**
