### PR TITLE
Adding DnD feature

### PR DESCRIPTION
**Pull request by manolo**
connected to #1

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/8)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[demo/index.html, line 37 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9boL4G7ezOQdM-eAdL:-K9boL4HyCu0oZHA6B6b:-424894579) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/demo/index.html#L37)):*
We might consider adding a custom drop label example and adding documentation on customising drop label. Not a blocker for MVP though.

---

*[test/adding-files.html, line 105 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9blbGEoDZa568neqTj:-K9blbGFmGSshhQuARrK:263137474) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/test/adding-files.html#L105)):*
We should either test for having a file in event.details, or simplify it like: `upload.addEventListener('file-add', fileAddSpy);`

---

*[test/drag-drop.html, line 0 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bmVnBXL1P82a4MQPg:-K9bmVnBXL1P82a4MQPh:187110234) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/test/drag-drop.html#L0)):*
Empty file.

---

*[vaadin-upload.html, line 36 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bmbHeSIsBiL4cbXxI:-K9bmbHeSIsBiL4cbXxJ:428737865) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/vaadin-upload.html#L36)):*
Add an empty line between CSS blocks please.

---

*[vaadin-upload.html, line 54 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bnBqn82mA0W1CyAcr:-K9bnBqn82mA0W1CyAcs:-696646463) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/vaadin-upload.html#L54)):*
Let's add a default fallback label text in content node like: `<content>Drop your files here...</content>`.

---

*[vaadin-upload.html, line 75 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bpNR0-vYkEsITM9YI:-K9bpNR0-vYkEsITM9YJ:1164885501) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/vaadin-upload.html#L75)):*
Is there a reason of having the events documentation above properties defenition? Would it make sense to follow the order of these sections rendered by iron-component-page?

1. Properties

2. Methods

3. Events

4. Behaviors

---

*[vaadin-upload.html, line 84 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bp6bnRJm_7v4k0X4S:-K9bp6bo1-8pHaqLgn89:-1191808374) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/vaadin-upload.html#L84)):*
Please add API documentation for this property.

---

*[vaadin-upload.html, line 112 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bm6z7eTjf7QbnoR8A:-K9bm6z7eTjf7QbnoR8B:837213586) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/vaadin-upload.html#L112)):*
Instead of `function(file) { this.add_file(file); }.bind(this)` we can safely write this._addFile.bind(this).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[test/adding-files.html, line 105 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9blbGEoDZa568neqTj:-K9fPlYG9yzhqyat1u9b:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/test/adding-files.html#L105)):*
Done.

---

*[vaadin-upload.html, line 36 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bmbHeSIsBiL4cbXxI:-K9fPtY92YH6DX108HDs:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/vaadin-upload.html#L36)):*
Done.

---

*[vaadin-upload.html, line 54 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bnBqn82mA0W1CyAcr:-K9fQHXNY6w9PDIEu824:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/vaadin-upload.html#L54)):*
Done.

---

*[vaadin-upload.html, line 75 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bpNR0-vYkEsITM9YI:-K9fQWX2Z25hlWnPKfiP:124977586) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/vaadin-upload.html#L75)):*
It was repeated, I did move all events to the bottom in other PR, but the rebase duplicated them. Now everything is after the Polymer(); which seems the convention in polymer.

---

*[vaadin-upload.html, line 84 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bp6bnRJm_7v4k0X4S:-K9fQwzBqk9HpaQEb-uH:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/vaadin-upload.html#L84)):*
Done.

---

*[vaadin-upload.html, line 112 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bm6z7eTjf7QbnoR8A:-K9fR7XYXPUpdJcv7TYW:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/vaadin-upload.html#L112)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/drag-drop.html, line  \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8#-K9bmVnBXL1P82a4MQPg:-K9fVQxTTdsa1RS4BJvf:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/6c2f82ea1d5c858921f95203d320d7d17f1e0e95/test/drag-drop.html#L)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/8)*

**Pull request merged**
