### PR TITLE
Fix/add file tests

### PR DESCRIPTION
**Pull request by platosha**
connected to #1

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/10)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/adding-files.html, line 40 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/10#-K9h5z6gIL7pXA0Qq-ib:-K9h5z6gIL7pXA0Qq-ic:830950729) ([raw file](https://github.com/vaadin/vaadin-upload/blob/607b7d89a55df62b4c49318b27066ed86453821b/test/adding-files.html#L40)):*
In common.js we have a describeSkipIf which probably we could use, as well as normally we have booleans there to identify browsers

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/10)*

**Comment by platosha** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/adding-files.html, line 40 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/10#-K9h5z6gIL7pXA0Qq-ib:-K9khLiNdf4ldA9baDHx:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/607b7d89a55df62b4c49318b27066ed86453821b/test/adding-files.html#L40)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/10)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/common.js, line 12 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/10#-K9ki83mqGVLvlpmzTL5:-K9ki83mqGVLvlpmzTL6:-1202970276) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a6cb9bf27d8a1735b43d49dddb5569f992be0335/test/common.js#L12)):*
I'd rather reg like in the ios flag, they are more declarative and maintainable from my point of view

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/10)*

**Comment by platosha** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/common.js, line 12 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/10#-K9ki83mqGVLvlpmzTL5:-K9kilvGnpKv6t3vTt1p:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/a6cb9bf27d8a1735b43d49dddb5569f992be0335/test/common.js#L12)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/10)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/10)*

**Pull request merged**
