### PR TITLE
Adding multiple and accept attributes

### PR DESCRIPTION
**Pull request by manolo**
Connected to #1

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/16)

### CODE REVIEW

**Comment by platosha** [comment]
Feels incomplete. If we’re adding `multiple` property, we should handle the disabled case and stop accepting files when a single file is already added. The same for `accept` property, we have to implement validation and filtering of dragged/dropped files then.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16#-:-KA0kxE8yK-hFzL1mvAl:377523805)*

**Comment by manolo** [comment]
Partially agree, multiple in this case does not mean that you cannot upload multiple files, but you only can select one per click. That might be useful in mobile to select one picture. 
I didn't want to complicate this PR, just reflect those properties to the native input file and be able to implement the user test, we can add more controls and tests in the future. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16#-:-KA17aigUK8Ti6zoPhqV:1759893450)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 207 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16#-KA4IRNQhwHueL6bGpSu:-KA4IRNQhwHueL6bGpSv:-1116088243) ([raw file](https://github.com/vaadin/vaadin-upload/blob/26664e04d77b772f9a6bddfa7967daf9cb8e9e75/vaadin-upload.html#L207)):*
Would prefer `nomultiple` here, similar to `nodrop` in the other PR, `noink` for paper elements and `novalidate` for HTML5 Form.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 207 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16#-KA4IRNQhwHueL6bGpSu:-KA4THvQrQNo6bWH9wiW:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/26664e04d77b772f9a6bddfa7967daf9cb8e9e75/vaadin-upload.html#L207)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16)*

**Comment by platosha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 437 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16#-KA4f_703hAsFbr5G_M0:-KA4f_703hAsFbr5G_M1:284191349) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f2d7e3679c45924bcc1168b523b192b8bcec1602/vaadin-upload.html#L437)):*
`'File is too big.'`, perhaps? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 437 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16#-KA4f_703hAsFbr5G_M0:-KA4h8d24AfwFdr9Hy2v:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f2d7e3679c45924bcc1168b523b192b8bcec1602/vaadin-upload.html#L437)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/16)*

**Pull request merged**
