### PR TITLE
Update screenshots

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/71)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/img/vaadin-upload-overview.png, line 0 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71#-KD7yn3iECh7jKCgPZ7C:-KD7yn3jIwinr8yw2lM0:-26985046) ([raw file](https://github.com/vaadin/vaadin-upload/blob/528d51cdffe712be6dee8154d67354febb88ef02/docs/img/vaadin-upload-overview.png#L0)):*
“file too big” is incorrect in English, I think. Should be either “too big file”, or “the file is too big”.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/img/vaadin-upload-overview.png, line  \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71#-KD7yn3iECh7jKCgPZ7C:-KD83IXUghzPr67wmPf3:1556110483) ([raw file](https://github.com/vaadin/vaadin-upload/blob/528d51cdffe712be6dee8154d67354febb88ef02/docs/img/vaadin-upload-overview.png#L)):*
Well, that is a message returned by and existing servlet causing the error.
I think it's not significant for the screenshot,  I would rather not have to modify compile and deploy the servlet.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/img/vaadin-upload-overview.png, line  \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71#-KD7yn3iECh7jKCgPZ7C:-KD84v90s5LGLtd1YrRf:-1163134410) ([raw file](https://github.com/vaadin/vaadin-upload/blob/528d51cdffe712be6dee8154d67354febb88ef02/docs/img/vaadin-upload-overview.png#L)):*
The previous screenshot contained another kind of error, without a server message. Could we make it this way? Otherwise it could make an impression that upload gives you incorrect message.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71)*

**Comment by manolo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/img/vaadin-upload-overview.png, line  \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71#-KD7yn3iECh7jKCgPZ7C:-KD8Xdr9IKJd_hx9vmwt:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/528d51cdffe712be6dee8154d67354febb88ef02/docs/img/vaadin-upload-overview.png#L)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71)*

**Comment by platosha** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/img/vaadin-upload-overview.png, line  \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71#-KD7yn3iECh7jKCgPZ7C:-KD8ZCxbjSodoMZDpK5u:-204428109) ([raw file](https://github.com/vaadin/vaadin-upload/blob/528d51cdffe712be6dee8154d67354febb88ef02/docs/img/vaadin-upload-overview.png#L)):*
Well, well, well... The red border is now 4px in the screenshot, but should be 2px master. Busted, you screenshot editor. :-)

You can mimic the error on any file element in web inspector with these commands:
```
$0.set('file.error', 'Server Unavailable');
$0.set('file.complete', false);
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71)*

**Comment by manolo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/img/vaadin-upload-overview.png, line  \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71#-KD7yn3iECh7jKCgPZ7C:-KD8cYvZnkx_QDO3uIHE:-121231876) ([raw file](https://github.com/vaadin/vaadin-upload/blob/528d51cdffe712be6dee8154d67354febb88ef02/docs/img/vaadin-upload-overview.png#L)):*
Previous committed image as well had different progress sizes, that was because I was using some zoom out in my chrome which produces some visual noise and inaccurate borders.

All progress bar have now the same height. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/71#-:-KD8q_5XGYzkH-4Nz9vF:1417088721)*

**Pull request merged**
