### PR TITLE
Initial lumo theme

### LINKED ISSUE #237: Implement new default theme
Mockup:
lumo-upload

New icons should be added to the `vaadin-lumo-styles` package.

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #237 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/239)

### CODE REVIEW

**Comment by tomivirkki** [comment]
screenshot 2018-01-23 11 12 07

Few issues:
- The file names should not wrap on multiple lines
- File name overflow should use text-overflow ellipsis
- Long file names should not push the icons out of view
- Each file in the list should have a background color

**Comment by platosha** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-upload/239#-L3XLx0Q8V90jfu2o8PX:-L3XLx0RcgdkBOhLaDyW:b24t1tu) (no related file):*
It’s rather unpleasant that the element’s height jumps harsh when the file is complete or being removed. I would expect a smooth transition instead. Don't know if tweaks like that fits the scope of the issue though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/239)*

**Comment by platosha** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-upload/239#-L3XMtzHB6dKcldLfP5O:-L3XMtzIStx-AMrIVYFA:b-r8u0li) (no related file):*
See: https://cdn.vaadin.com/vaadin-core-elements/latest/vaadin-upload/demo/

The original Material Design `<vaadin-upload>` had a nice large drop zone with light border around and some padding inside:  Having large drop zone with clearly visually defined border helps to use it a lot. What we have now here is a small drop-zone with no padding and no border, hard to say where should I point my files to, harder to target with moueasy to miss.

Additionally, the drag over feedback was much more prominent: the drop zone border changes to solid blue, and the background tints a lot, confirming that this area is ready to receive the files you drag. What we have here is just a text color change, again easy to miss.

For mobile devices, where drag-and-drop is not in use, we hidden the drop zone and removed the padding.

Somehow this is completely missing in the mockups. @jouni was that intentional? Should we maybe bring the drop zone back?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/239)*

**Comment by jouni** [comment]
> Each file in the list should have a background color
Actually, no, that’s not needed.

> For mobile devices, where drag-and-drop is not in use, we hidden the drop zone and removed the padding.
> Somehow this is completely missing in the mockups. @jouni was that intentional? Should we maybe bring the drop zone back
No, no need to show the drop zone on mobile devices. The mockup is basically just for desktop, but showing a case where the upload element doesn’t have enough horizontal space to fit in.

**Comment by jouni** [comment]
@platosha, you’re right, the previous Material design version had better usability.

I didn’t want to add padding by default so that the upload button’s left edge aligns the same as other buttons or fields by default (when stacked in a form for example). Because of that, a border doesn’t really work visually as it would touch the upload button.

I think the “Drop files here” label is a large enough target, and the developer can make it larger by adding a custom padding (and a border to indicate the larger area) if needed.

I agree on the drop indication style, that it’s probably too subtle. I pushed for simplicity here again (I had a few alternatives I played with before settling), but maybe slightly too far.

**Comment by jouni** [comment]
Actually, I wanted to redesign the whole button area, but opted to keep the changes to a minimum. I’ll share one idea which should help with drop indication at least.

**Comment by jouni** [comment]
Here’s a prototype of an alternative drop indication: http://jsbin.com/semevem

**Comment by platosha** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-upload/239#-L3XLx0Q8V90jfu2o8PX:-L3cT1Suv7LjIibNE4QS:bmpfl1g) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

It’s rather unpleasant that the element’s height jumps harsh when the file is complete or being removed. I would expect a smooth transition instead. Don't know if tweaks like that fits the scope of the issue though.
</blockquote></details>

OK File state transitions, pretty much, depend on #243, so not a blocker here.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-upload/239#-L3XMtzHB6dKcldLfP5O:-L3cTLBwTIxw09eyRTGW:bkcq8k0) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

See: https://cdn.vaadin.com/vaadin-core-elements/latest/vaadin-upload/demo/

The original Material Design `<vaadin-upload>` had a nice large drop zone with light border around and some padding inside:  Having large drop zone with clearly visually defined border helps to use it a lot. What we have now here is a small drop-zone with no padding and no border, hard to say where should I point my files to, harder to target with moueasy to miss.

Additionally, the drag over feedback was much more prominent: the drop zone border changes to solid blue, and the background tints a lot, confirming that this area is ready to receive the files you drag. What we have here is just a text color change, again easy to miss.

For mobile devices, where drag-and-drop is not in use, we hidden the drop zone and removed the padding.

Somehow this is completely missing in the mockups. @jouni was that intentional? Should we maybe bring the drop zone back?
</blockquote></details>

OK Done the dropzone style myself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/239)*

**Comment by jouni** [comment]
What’s your take on aligning the upload button with other buttons/fields horizontally? You don’t see it as a problem, I suppose? Would `--lumo-space-s` be enough padding?

My initial thought was to make the host an inline-block, but I suppose block is a better default (easy to override anyways). Let’s go with that.

I think this is “good enough” to merge, but some work is still needed to polish it:
- If we leave the outer dashed border, the last file in the list should not have the bottom border
- Not enough space between files in the list (the file name and the border above it)
- No hover styles for the buttons in the file item
- Error icon is misaligned
- Error text should use error color (was missing from the mockup, my mistake)

Question: should we keep the progress bar for an errored file visible? I made it hidden in the mockup, but is it actually relevant information (uploaded failed halfway uploading, and maybe you want to know how much you uploaded)? Also, should we make the progressbar use the error color in that state also?

**Comment by jouni** [comment]
I can agree on adding back the border and padding on the host, if I can be assured that we’ll redesign this in the next major version 😄

**Comment by jouni** [comment]
Can we update the default `i18n` text at the same time? The button label should have the ellipsis, not the drop zone label (”Upload Files…/Select File…” and “Drop files here”), like in the mockups.

**Comment by jouni** [comment]
Everywhere you use a shade color now, switch to the contrast version, so the dark version works automatically.

**Comment by jouni** [comment]
Whever you set the `color` property, use the “text” color version instead of the default color versions. This ensures proper contrast for both light and dark themes. I.e. `--lumo-primary-text-color` vs. `--lumo-primary-color` or `--lumo-error-text-color` vs. `--lumo-error-color`.

**Comment by platosha** [comment]
Sorry, merge was not intentional.

Will make another polish PR now.

**Comment by jouni** [comment]
Just to add one thing I just realized: it’s safer to follow the previous design, as we did UX test with that (IIRC), and my new ideas are not validated and possibly have the negative effects on usability like @platosha suggested.

**Pull request merged**
