### PR TITLE
Restore file element state before removal

### LINKED ISSUE #198: Removing files from the list has glitches on Polymer 2
Polymer 2's `<dom-repeat>` re-uses the element instances even for different items. This causes some issues for the `<vaadin-upload>`'s file list when files are removed because the elements in the list have implicit state that's not dictated by the item.

The [restamp](https://github.com/Polymer/polymer/pull/4363) property would fix this but since it's not yet available, this needs to be fixed somehow else.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #198

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/199)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-upload-file.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/199#-KmBvFtnbucUqeTxJ9Lm:-KmBvFtnbucUqeTxJ9Ln:bmwbhmx) ([raw file](https://github.com/vaadin/vaadin-upload/blob/61ec70fa011ae11af165bca2455e96c9719d84d1/vaadin-upload-file.html#L275)):*
> ```HTML
>     ready: function() {
>       this.addEventListener('animationend', function(e) {
>         if (e.animationName.indexOf('fade-out') > -1) {
> ```

Can we use a strict check here `e.animationName === 'fade-out'`?

---

*[vaadin-upload-file.html, line 284 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/199#-KmBsHir_Vc1FPJp87ee:-KmBsHir_Vc1FPJp87ef:b6roqvt) ([raw file](https://github.com/vaadin/vaadin-upload/blob/61ec70fa011ae11af165bca2455e96c9719d84d1/vaadin-upload-file.html#L284)):*
> ```HTML
>       if (abort) {
>         this.toggleClass('fade-out', true);
>         
> ```

Spaces indent on the empty line, please remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/199)*

**Comment by tomivirkki** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-upload-file.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/199#-KmBvFtnbucUqeTxJ9Lm:-KmBx7Kjblyu3T53iY3_:b-f5xznw) ([raw file](https://github.com/vaadin/vaadin-upload/blob/61ec70fa011ae11af165bca2455e96c9719d84d1/vaadin-upload-file.html#L275)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Can we use a strict check here `e.animationName === 'fade-out'`?
</blockquote></details>

On Polymer 1 shady the animation name is scoped to something like "fade-out-vaadin-upload-file-0". There are tests that verify this but added a comment here also.

---

*[vaadin-upload-file.html, line 284 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/199#-KmBsHir_Vc1FPJp87ee:-KmByLw2EZkyzNYeKBYf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/61ec70fa011ae11af165bca2455e96c9719d84d1/vaadin-upload-file.html#L284)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Spaces indent on the empty line, please remove.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/199)*

**Comment by limonte** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/199)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload-file.html, line 275 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/199#-KmBvFtnbucUqeTxJ9Lm:-KmC-sTmWcbaV4ww8hjE:bnlxa4u) ([raw file](https://github.com/vaadin/vaadin-upload/blob/61ec70fa011ae11af165bca2455e96c9719d84d1/vaadin-upload-file.html#L275)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

On Polymer 1 shady the animation name is scoped to something like "fade-out-vaadin-upload-file-0". There are tests that verify this but added a comment here also.
</blockquote></details>

OK wow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/199#-:-KmC-ya156h9MlhBJ4Wo:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/199#-:-KmC013cl3F7k5bPuLtb:bnfp4nl)*

**Pull request merged**
