### PR TITLE
Nice File Initial Implementation

### PR DESCRIPTION
**Pull request by platosha**
Connected to #1

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/13)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[vaadin-upload-file.html, line 65 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-U9sQIfSvec5OcM6T:-KA-U9sQIfSvec5OcM6U:1531179366) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload-file.html#L65)):*
For some reason these colors do not work to me.
Grey should be in the beginning, blue when progressing or succeed, and red on error. I always see greys though

---

*[vaadin-upload.html, line 77 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-MAvQ0obuWCIvIkow:-KA-MAvRmyOFd72vN8hg:64635116) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L77)):*
Based on designs, drop area should be above file list. This is from other PR, but could you move?

---

*[vaadin-upload.html, line 296 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-NRFE-X6UzDzVkvxz:-KA-NRFE-X6UzDzVkvy-:-738047351) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L296)):*
when the code below is very small I would include all of them in the if block an negate the block, the code is readable enough and we save some size, even inlining vars helps to reduce size:

This saves 14 chars
```
      var evt = this.fire('upload-retry', {file: file, xhr: file.xhr}, {cancelable: true});
      if (!evt.defaultPrevented) {
        this.async(this._uploadFile.bind(this, file));
      }
```
or 

This saves 33 chars
```
      if (!this.fire('upload-retry', {file: file, xhr: file.xhr}, {cancelable: true}).defaultPrevented) {
        this.async(this._uploadFile.bind(this, file));
      }
```

It's just an idea for all these blocks returning at the beginning (gwt-devs always obsessed to reduce size :-) ), not blocking though

---

*[vaadin-upload.html, line 304 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-M_7jmQdojd8CZXRt:-KA-M_7jmQdojd8CZXRu:-1136694202) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L304)):*
missing @event block

---

*[vaadin-upload.html, line 310 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-QmfV8tOk6zdwT96P:-KA-QmfV8tOk6zdwT96Q:-2091035) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L310)):*
We have to set the file.abort flag as well, take a look to the upload onreadystatechange code

---

*[vaadin-upload.html, line 341 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-MQsIVRIgAA9MDwec:-KA-MQsIVRIgAA9MDwed:-1136694202) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L341)):*
missing @event block

---

*[vaadin-upload.html, line 369 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-Q1b0QsGHdP0u9EcA:-KA-Q1b16JE0WQc86gJP:-116759473) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L369)):*
I don't follow this 100%, but I think this code is confusing because the event names being the same in vaadin-upload and vaadin-file-upload, probably vaadin-file-upload should fire a file-retry instead of upload-retry 

To me the code would be clearer, either you change the event name or not:

```
    _onUploadRetry: function(event) {
      var file = Polymer.dom(event).rootTarget.file;
      if (file) {
        this._retryFileUpload(file);
      }
    }
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13)*

**Comment by platosha** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[vaadin-upload-file.html, line 65 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-U9sQIfSvec5OcM6T:-KA-lR2dsgkBAJmIyLPe:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload-file.html#L65)):*
Done.

---

*[vaadin-upload.html, line 77 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-MAvQ0obuWCIvIkow:-KA-lU196u2lvwiEqDGL:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L77)):*
Done.

---

*[vaadin-upload.html, line 296 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-NRFE-X6UzDzVkvxz:-KA-lW6d98759xB4wIf4:1011653778) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L296)):*
Alright, wrapped actions inside `if`, when applicable.

As for me, it was meaningfully better with `return`. It kinda represents that normal flow is to perform the following action, and the `defaultPrevented` case is just a rare case. It goes more similar with `defaultPrevented` checks in `_uploadFile` method, that also helps with reading.

And I would not make the event fire and a check on a single line, it's too hard to read.

---

*[vaadin-upload.html, line 304 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-M_7jmQdojd8CZXRt:-KA-mwflVBm39lQU9lFH:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L304)):*
Done.

---

*[vaadin-upload.html, line 310 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-QmfV8tOk6zdwT96P:-KA-mxQ6PETn-FziVn4m:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L310)):*
Done.

---

*[vaadin-upload.html, line 341 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-MQsIVRIgAA9MDwec:-KA-myDSbntDKnVaPlwn:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L341)):*
Done.

---

*[vaadin-upload.html, line 369 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-Q1b0QsGHdP0u9EcA:-KA-n-LT1GgV6Ly7J8bK:-1286989432) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fc84c249a1a8e9b6fbc9e4658c46c2bb76e06ee8/vaadin-upload.html#L369)):*
Resolved. Introduced `file-retry` and `file-abort` events in the file element.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13)*

**Comment by manolo** [comment]
Reviewed 1 of 3 files at r1, 2 of 3 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 383 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-qD-S58Ro1D8TlrHu:-KA-qD-S58Ro1D8TlrHv:-750162321) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ab78e4b306dbf817bbdf2108db2d97db457c4c4e/vaadin-upload.html#L383)):*
If I understand correctly, his should read:
Send this event to the component if you want a file to be removed.
Fired normalmente by buttons in the UI.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13)*

**Comment by manolo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-upload.html, line 339 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-rOuq-39jzTFOSkGg:-KA-rOuq-39jzTFOSkGh:-2124483945) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ab78e4b306dbf817bbdf2108db2d97db457c4c4e/vaadin-upload.html#L339)):*
This makes not sense to me, why a user is going to send an event to the uploader to remove a file with the default prevented set to true. ? 
If the user wants to cancel something should use upload-remove events

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13)*

**Comment by manolo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/common.html, line 8 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-t2A7oE6fNv99uc_M:-KA-t2A7oE6fNv99uc_N:1825501032) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ab78e4b306dbf817bbdf2108db2d97db457c4c4e/demo/common.html#L8)):*
IMO the user should not define these colors in the UI unless he want't to change the blue and red.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13)*

**Comment by platosha** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/common.html, line 8 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-t2A7oE6fNv99uc_M:-KA-vMFogsAKXBi7STK4:-988917763) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ab78e4b306dbf817bbdf2108db2d97db457c4c4e/demo/common.html#L8)):*
There's an import problem with `paper-icon-button`. It imports `"paper-styles/default-theme.html"`, which defines `--primary-color` CSS variable with some Polymer default value. That's why we had to import this file on the demo page before `paper-icon-button` does it, and override the colors after importing the theme.

---

*[vaadin-upload.html, line 339 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-rOuq-39jzTFOSkGg:-KA-seI68583Scei14PI:79824508) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ab78e4b306dbf817bbdf2108db2d97db457c4c4e/vaadin-upload.html#L339)):*
This event is not to be sent by user, but to be listened for. The use case is different here. The event is for keeping track when the file gets removed from the list, to be able to prevent it and handle differently or perform something in addition. The opposite of `file-add` event.

We might get rid of `file-add` and `file-remove` events, if everyone is happy to keep track of file list changes with just `files` array property binding.

---

*[vaadin-upload.html, line 383 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-qD-S58Ro1D8TlrHu:-KA-tm99BljbYxTIz9rh:1117111720) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ab78e4b306dbf817bbdf2108db2d97db457c4c4e/vaadin-upload.html#L383)):*
No, that's not true for `file-add` and `file-remove` events, you can't trigger actions in the upload by firing them. But that is true for `file-retry` and `file-abort` events of file element, which do act like action triggers for the upload. Added a similar note to those events.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-upload.html, line 339 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-rOuq-39jzTFOSkGg:-KA-yAV9iN2707z6ZaZl:1215247271) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ab78e4b306dbf817bbdf2108db2d97db457c4c4e/vaadin-upload.html#L339)):*
I get your point, the array could work but not inside the file-element itself which does not have the array reference unless it uses the parent instance.
My point is more related with the user composing a customised UI with customised file-elements, so firing the event is quite convenient to make the upload remove those files and clean everything etc.
Another option is remove those events and use Polymer array methods instead.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/common.html, line 8 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13#-KA-t2A7oE6fNv99uc_M:-KA03Jy4_y2O5xOP_Gom:335903665) ([raw file](https://github.com/vaadin/vaadin-upload/blob/ab78e4b306dbf817bbdf2108db2d97db457c4c4e/demo/common.html#L8)):*
Couldn't we change --primary-color by another thing? is there any blue in default-theme ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13)*

**Comment by manolo** [comment]
Reviewed 1 of 3 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/13)*

**Pull request merged**
