### PR TITLE
New: Modular Upload Components

### PR DESCRIPTION
**Pull request by stramel**
Hey all! :wave:

PTAL @manolo @jouni @marcushellberg @platosha @limonte 

I have finished building out what I had proposed in #201. This is just a first attempt and ready for some solid reviews.

A few notes:

- `vaadin-upload` element has remained with the goal of being 100% backwards compatible but built on the new components
- "uploaders" are in charge of "uploading" the file(s)
- "uploads" are in charge of validation and the initial addition of files.

There are still some things that are outstanding from being considered "complete" these are listed below
**TODO:** 
- [ ] Unit Tests
- [ ] Full Set of Demos
- [ ] Visual Regression Tests
- [ ] Customization slots
- [ ] Styling Parts and Variables/Mixins

**Bugs:**
- [ ] Dropzone doesn't always track dragged over properly... *sigh*

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/227)

### CODE REVIEW

**Comment by krumware** [comment]
Partttyyyyyy

**Comment by stramel** [comment]
Thinking a bit more about some aspects of this, I could see some more clean up and refactor that could happen. Could happen as an enhancement later as well. I will see if I can find time to do these changes.

**Comment by stramel** [comment]
Sadly, I don't have time to tackle this anymore during my day-to-day. This PR is pretty out of date now and some of the approaches may not make sense in P3. I am going to close this but hopefully some of the code can be useful for the future features.

**Comment by jouni** [comment]
😞 I feel quite ashamed that we failed to take the ball on this, and get this contribution merged. But like you said, I’m also hoping we can salvage some parts of it sometime later.

**Comment by stramel** [comment]
@jouni	No problem! I know you guys were quite busy with other tasks. I wish I could have got this finished up before switching jobs and before P3 landed. I think some of the clunky-ness of this PR will be cleaned up in the P3 version. 

I have great confidence in you and your team's ability to get the idea across the finish line 🏁

**Pull request closed without merging**
