### PR TITLE
Implementing autoUpload.

### PR DESCRIPTION
**Pull request by manolo**
connected to #1

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/9)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/common.html, line 59 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9#-K9gHkMh84ybI-GqsoFw:-K9gHkMh84ybI-GqsoFx:-2103030903) ([raw file](https://github.com/vaadin/vaadin-upload/blob/c3de457e9a8c1d41b98c766569d16db25e04805e/demo/common.html#L59)):*
does WebComponentsReady happen before any web-component in the page is created and after any web-component has been registered? I don't have a clear idea when this event is fired.

---

*[test/upload.html, line 115 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9#-K9gJb4wenWF5Je0e6tf:-K9gJb4wenWF5Je0e6tg:-1851968356) ([raw file](https://github.com/vaadin/vaadin-upload/blob/c3de457e9a8c1d41b98c766569d16db25e04805e/test/upload.html#L115)):*
shouldn't we spy that the modified url was actually  used when opening the xhr ?

---

*[vaadin-upload.html, line 231 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9#-K9gIm2Oa3_TBCh-xzO0:-K9gIm2Oa3_TBCh-xzO1:-1417295450) ([raw file](https://github.com/vaadin/vaadin-upload/blob/c3de457e9a8c1d41b98c766569d16db25e04805e/vaadin-upload.html#L231)):*
Since we use the file to store all properties related with it, I'd rather use file.uploadTarget  for instance

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r1, 2 of 4 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/common.html, line 59 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9#-K9gHkMh84ybI-GqsoFw:-K9g__Pfh5le0yfbgFnS:-249593406) ([raw file](https://github.com/vaadin/vaadin-upload/blob/c3de457e9a8c1d41b98c766569d16db25e04805e/demo/common.html#L59)):*
Yes, by definition it's fired when all imports were loaded and all any elements registered in them were upgraded. That's a bit different from HTMLImports.whenReady, which is invoked just after imports were loaded.

---

*[test/upload.html, line 115 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9#-K9gJb4wenWF5Je0e6tf:-K9gmmATwtvb90wFzBQn:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/c3de457e9a8c1d41b98c766569d16db25e04805e/test/upload.html#L115)):*
Done.

---

*[vaadin-upload.html, line 231 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9#-K9gIm2Oa3_TBCh-xzO0:-K9gmL97s-vIIOuCYtum:-1455431037) ([raw file](https://github.com/vaadin/vaadin-upload/blob/c3de457e9a8c1d41b98c766569d16db25e04805e/vaadin-upload.html#L231)):*
Very nice idea, done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[demo/common.html, line 59 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9#-K9gHkMh84ybI-GqsoFw:-K9gon-MrYitKxwBp9V9:1853393605) ([raw file](https://github.com/vaadin/vaadin-upload/blob/c3de457e9a8c1d41b98c766569d16db25e04805e/demo/common.html#L59)):*
My concern is that some vaadin-upload could be instantiated before the event happens, I mean vaadin-upload.html is imported, and  some`<vaadin-upload>` could be created, but HTMLImports.whenReady might be waiting for other components to be registered

---

*[test/upload.html, line 120 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9#-K9goWQ6vAnVNH353nWe:-K9goWQ7juXEspEHKIej:436474952) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fe94e8440e8be5a5573a26e20972d7c5e3320cac/test/upload.html#L120)):*
We don't need to continue with the original workflow once we have asserted that url was correctly set

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/common.html, line 59 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9#-K9gHkMh84ybI-GqsoFw:-K9gsNLtO_ZX5kour1UJ:685242761) ([raw file](https://github.com/vaadin/vaadin-upload/blob/c3de457e9a8c1d41b98c766569d16db25e04805e/demo/common.html#L59)):*
It's not the case, because I'm modifying the element prototype below. The prototype modifications are applied to all current and future instances.

---

*[test/upload.html, line 120 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9#-K9goWQ6vAnVNH353nWe:-K9gt7BbuQlOSsJpjUYg:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/fe94e8440e8be5a5573a26e20972d7c5e3320cac/test/upload.html#L120)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/9)*

**Pull request merged**
