### PR TITLE
Disable drop on mobile

### PR DESCRIPTION
**Pull request by manolo**
Connected to #1

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/15)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-upload.html, line 101 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15#-KA0ZVG0dOPbly6Vb6O-:-KA0ZVG0dOPbly6Vb6O0:-1876462261) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f75efbf2cd9addeffe50ab7c9741fbd8072b94a8/vaadin-upload.html#L101)):*
Would you, please, rename it to “nodrop” to make it more meaningful? And add a doc comment with mention of different default value on mobile.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 101 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15#-KA0ZVG0dOPbly6Vb6O-:-KA0eNdAfUHWpcV6xalt:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f75efbf2cd9addeffe50ab7c9741fbd8072b94a8/vaadin-upload.html#L101)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-upload.html, line 188 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15#-KA0j_FTrI64QMddLZKU:-KA0j_FTrI64QMddLZKV:139417401) ([raw file](https://github.com/vaadin/vaadin-upload/blob/96d18bc75199196afa16ac0253c034193d7b464b/vaadin-upload.html#L188)):*
Throws error `"nodrop not defined"`. Should be `!this.nodrop`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-upload.html, line 188 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15#-KA0j_FTrI64QMddLZKU:-KA18X9Yzbod-bGYfCRf:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/96d18bc75199196afa16ac0253c034193d7b464b/vaadin-upload.html#L188)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15)*

**Comment by platosha** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-upload-file.html, line 99 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15#-KA4FYGKR9-gIo0pJ8HK:-KA4FYGKR9-gIo0pJ8HL:-486818301) ([raw file](https://github.com/vaadin/vaadin-upload/blob/8e191c84cc44ab7b79d2dbd5d4fb24c5b130fe1e/vaadin-upload-file.html#L99)):*
There's something wrong. Setting these colors to the same color value would remove the visible progress indication.

If that is what are you trying to achieve, then we also need to make fallback colors  of the same value. Now the fallback colors are red and blue for active part and container.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-upload-file.html, line 99 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15#-KA4FYGKR9-gIo0pJ8HK:-KA4SluY__E7GLWit84t:-430541278) ([raw file](https://github.com/vaadin/vaadin-upload/blob/8e191c84cc44ab7b79d2dbd5d4fb24c5b130fe1e/vaadin-upload-file.html#L99)):*
Yes, when the uploads fails the bar should be red, no matter what the progress was. The uploader has nothing to do until the user retries, so no reason to have an indeterminate movement either

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15)*

**Comment by platosha** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15)*

**Comment by platosha** [comment]
Breaks drop file tests on mobile. We should disable the drop tests on mobile anyways.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15#-:-KA4n-jv74wSwRlA-gwF:1339855405)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/15)*

**Pull request merged**
