### PR TITLE
Document default values

### PR DESCRIPTION
**Pull request by manolo**
Connected to #51

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/54)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-upload.html, line 208 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54#-KCz285F2SsH5SK0GEXx:-KCz285F2SsH5SK0GEXy:-2045025161) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9482ef175e43bda8af14de009319589f8223eccb/vaadin-upload.html#L208)):*
Some rewording suggestions:
Define<b>s</b> whether....supports <b>dropping</b> files....
...because <strike>almost</strike> mobile devices don't support drag events <b>in general</b>.

Setting it <strike>to</strike> false....in touch devices, ...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54)*

**Comment by samiheikki** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[vaadin-upload-file.html, line 239 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54#-KCz7Cb-CBqcM4cPYdie:-KCz7Cb-CBqcM4cPYdif:1070927438) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9482ef175e43bda8af14de009319589f8223eccb/vaadin-upload-file.html#L239)):*
lowercase `Listened`

---

*[vaadin-upload-file.html, line 240 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54#-KCz7NWolhQ-8VdNxMoc:-KCz7NWolhQ-8VdNxMod:-1894601182) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9482ef175e43bda8af14de009319589f8223eccb/vaadin-upload-file.html#L240)):*
Should it be `for this file`? Not sure.

---

*[vaadin-upload-file.html, line 250 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54#-KCz7gt0uq7BVI1AA74s:-KCz7gt0uq7BVI1AA74t:331699472) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9482ef175e43bda8af14de009319589f8223eccb/vaadin-upload-file.html#L250)):*
`elemnt`

---

*[vaadin-upload-file.html, line 264 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54#-KCz81ExQ1IDe9nA6y79:-KCz81EyCx2UO1TDWHEh:1723458692) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9482ef175e43bda8af14de009319589f8223eccb/vaadin-upload-file.html#L264)):*
Extra space before `@param`? Extra space between `from the` and `upload`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-upload-file.html, line 240 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54#-KCz7NWolhQ-8VdNxMoc:-KCzRTG7w2Vc-TA8U0HA:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9482ef175e43bda8af14de009319589f8223eccb/vaadin-upload-file.html#L240)):*
Done.

---

*[vaadin-upload-file.html, line 250 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54#-KCz7gt0uq7BVI1AA74s:-KCzRUdbAZd37pzhJPAG:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9482ef175e43bda8af14de009319589f8223eccb/vaadin-upload-file.html#L250)):*
Done.

---

*[vaadin-upload-file.html, line 264 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54#-KCz81ExQ1IDe9nA6y79:-KCzRVWNO-VZaTTBl3wN:-1285727651) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9482ef175e43bda8af14de009319589f8223eccb/vaadin-upload-file.html#L264)):*
That's ok for the hydrolysis parser

---

*[vaadin-upload.html, line 208 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54#-KCz285F2SsH5SK0GEXx:-KCzRwgyQdHiGRPywD6J:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9482ef175e43bda8af14de009319589f8223eccb/vaadin-upload.html#L208)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-upload-file.html, line 239 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54#-KCz7Cb-CBqcM4cPYdie:-KCzS4I3W_QZUM012Z0q:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/9482ef175e43bda8af14de009319589f8223eccb/vaadin-upload-file.html#L239)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54)*

**Comment by samiheikki** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54)*

**Comment by manolo** [comment]
Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/54)*

**Comment by Saulis** [comment]
Retargeted to master in #70

**Pull request closed without merging**
