### PR TITLE
Feature/documentation stubs

### PR DESCRIPTION
**Pull request by platosha**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/3)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/overview.asciidoc, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SmE3s-ToMkh_WpvSz:-K9SmE3s-ToMkh_WpvT-:-802173347) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/docs/overview.asciidoc#L13)):*
into the component.
which opens the native file dialog for selecting the file or files to process.

---

*[docs/overview.asciidoc, line 15 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9Smb5k9HurYF--_lkN:-K9Smb5lvlREw3KlJvb3:-125094217) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/docs/overview.asciidoc#L15)):*
are displayed in a file queue

---

*[docs/overview.asciidoc, line 17 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SmgOVw9XpQ5_0g0o4:-K9SmgOVw9XpQ5_0g0o5:125518139) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/docs/overview.asciidoc#L17)):*
In the prototype the developer can select how many files are concurrently being uploaded. It's an important feature because uploading 20 files could collapse the line and none of them being uploaded after a long while, we could implement it later though.

---

*[index.html, line 5 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SnV6L1erG53ol8vCh:-K9SnV6L1erG53ol8vCi:1570770894) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/index.html#L5)):*
I'd say this element

---

*[README.md, line 25 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SnZmZ0J0RghPTMaVZ:-K9SnZmZ0J0RghPTMaV_:967891437) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/README.md#L25)):*
-g should be preceded by sudo (linux & mac)

---

*[README.md, line 49 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SnnszqEsHbZBJ-mJs:-K9SnnszqEsHbZBJ-mJt:-633678218) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/README.md#L49)):*
vaadin-upload

---

*[vaadin-upload.html, line 4 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SnrxyA2bcqq8ovaRF:-K9SnrxyA2bcqq8ovaRG:1753802815) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/vaadin-upload.html#L4)):*
program or element ? we might discuss with PO

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3)*

**Comment by platosha** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/overview.asciidoc, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SmE3s-ToMkh_WpvSz:-K9WCRAatWgJqDoPVCEm:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/docs/overview.asciidoc#L13)):*
Done.

---

*[docs/overview.asciidoc, line 15 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9Smb5k9HurYF--_lkN:-K9WCSFYF2KwLU1FMpX3:659207507) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/docs/overview.asciidoc#L15)):*
I still prefer to say “file list” here. This sentence is about just the presentation of files, not about the action performed with them or underlying mechanisms.

---

*[docs/overview.asciidoc, line 17 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SmgOVw9XpQ5_0g0o4:-K9W6kwBxQ50hi0sSCtC:897986033) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/docs/overview.asciidoc#L17)):*
20 files would never be uploaded simultaneously because of the browser’s limit of simultaneous connections to the same hostname. In this case some of the uploading XHRs would be scheduled later by browser. See: http://www.browserscope.org/?category=network 

But yes, we agreed to document features while we add them. Let’s mention concurrency limit and queueing support when we would be adding them.

---

*[index.html, line 5 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SnV6L1erG53ol8vCh:-K9WClSZOKxqvZh6A_0b:-651713797) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/index.html#L5)):*
Answered below.

---

*[README.md, line 25 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SnZmZ0J0RghPTMaVZ:-K9W8qJF7JlkLZL1BVfF:1253370804) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/README.md#L25)):*
At least on my mac it works without sudo. Also, the vaadin-combo-box README doesn't mention sudo there.

---

*[README.md, line 49 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SnnszqEsHbZBJ-mJs:-K9WCwDuoYokUNUtmTYn:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/README.md#L49)):*
Done.

---

*[vaadin-upload.html, line 4 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SnrxyA2bcqq8ovaRF:-K9WAwbR_s48wPt-OJpa:395045866) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/vaadin-upload.html#L4)):*
This particular header was copied from the vaadin-combo-box. If you want to change this header, we would likely need to do that in a separate process/task for all our elements. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3)*

**Comment by manolo** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 25 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SnZmZ0J0RghPTMaVZ:-K9WGAh_OVLvbfUWY3w9:-77239742) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/README.md#L25)):*
Grid notices about that https://github.com/vaadin/vaadin-grid

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 25 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3#-K9SnZmZ0J0RghPTMaVZ:-K9WtVtBv0NYwRAHjUOn:888849822) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1a7336498f7e335c7fd77c0f0d0ceb8751ece8e0/README.md#L25)):*
We need to discuss this with the team and come up with some general decision. Splitted this out to the separate issue: https://waffle.io/vaadin/vaadin-core-elements/cards/56b09b0fb689206800774f41

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/3)*

**Pull request merged**
