### PR TITLE
Fix/disabled dropping

### LINKED ISSUE #29: Remove the droppable indication when dropping is disabled
On some cases (e. g., for mobile), the developer might disable the drop files support by setting `nodrop` attribute/property. This makes the element to not handle the drop, removes the drop zone border, padding and label.

Though, the element still indicates the drop support if someone try to drag files over it with the ripple and cursor reaction. We should probably remove that indication as well.

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #29

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/35)

### CODE REVIEW

**Comment by manolo** [comment]
LGTM

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-:-KBvGOD4lHBn7pcf2r4C:676834233)*

**Comment by platosha** [comment]
Needs to be rebased.

Also, the validation feedback is still not here.

For example, try the last demo in demo/index.html, which allows only up to 3 PDF files below 1 MB each. What feels wrong with it is that it still indicates enabled dropping (cursor and ripple) for any file you drag over the upload, even if dragging non-PDF file, or too big file, or 3 files has already been added. So there's no validation feedback on drag-over.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-upload.html, line 340 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-KC0C_NLEsqUrxsVFqKj:-KC0C_NMBUld4pTbrjvN:1713361740) ([raw file](https://github.com/vaadin/vaadin-upload/blob/b9ff3b9aac762cf40298656d5134137af23f8441/vaadin-upload.html#L340)):*
Btw, it would make sense to indicate dropEffect = 'copy' in case if we do accept drop.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-:-KC0CUbX3oQjWHExz-0q:-760167238)*

**Comment by samiheikki** [comment]
dragover event doesn't seem to provide any way to access the files.  I think that I can only validate `maxFiles`.  

[http://stackoverflow.com/questions/11065803/determine-what-is-being-dragged-from-dragenter-dragover-events](http://stackoverflow.com/questions/11065803/determine-what-is-being-dragged-from-dragenter-dragover-events)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-:-KCFMfUpkdAA4sdS2dtm:-871419982)*

**Comment by platosha** [comment]
Right. Except in Chrome and Opera12+, which expose `event.dataTransfer.items` in dragover event, where the number of files and their types could be determined. Could we do that if `dataTransfer.items` object is present?

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-upload.html, line 336 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-KCGAEodFg1rx-LfOqRq:-KCGAEodFg1rx-LfOqRr:1273697335) ([raw file](https://github.com/vaadin/vaadin-upload/blob/4c7594144311be3c043d3586168f829a81d596d6/vaadin-upload.html#L336)):*
This check doesn't make sense. It checks the number of already added files against the limit and has nothing to do with the files the user is dragging over. That's useless here, I think.

---

*[vaadin-upload.html, line 340 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-KCGArsi5iuLK9iteObt:-KCGArsi5iuLK9iteObu:-1914937751) ([raw file](https://github.com/vaadin/vaadin-upload/blob/4c7594144311be3c043d3586168f829a81d596d6/vaadin-upload.html#L340)):*
The dragover event is fired multiple times, but the dropEffect would be set to 'copy' only if the upload element was `!this.dragover`. Please move this line out of the `if (!this.dragover...)`. And restructure this method’s code a bit, maybe.

You can find out if you set it correctly by checking the mouse cursor look when you're dragging files over the upload. Should be like this:

- Cursor indicates copy (+) when drop is enabled
- Cursor indicates nothing when drop is disabled

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-:-KCG3brsDTOOsRRDENvs:-1919996578)*

**Comment by samiheikki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-upload.html, line 340 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-KC0C_NLEsqUrxsVFqKj:-KCGWBQYFBlDLQjuCgpT:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/b9ff3b9aac762cf40298656d5134137af23f8441/vaadin-upload.html#L340)):*
Done.

---

*[vaadin-upload.html, line 336 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-KCGAEodFg1rx-LfOqRq:-KCGUk8EHq98jU-4yXSt:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/4c7594144311be3c043d3586168f829a81d596d6/vaadin-upload.html#L336)):*
Done.

---

*[vaadin-upload.html, line 340 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-KCGArsi5iuLK9iteObt:-KCGWB-xxPtd18umeHy1:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/4c7594144311be3c043d3586168f829a81d596d6/vaadin-upload.html#L340)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-:-KCKJsZUXD72LqqR2RCV:1417088721)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-upload.html, line 621 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-KCKbZx_T8SoBdNmNUmL:-KCKbZxaKUkljtuEMNuV:-2125202340) ([raw file](https://github.com/vaadin/vaadin-upload/blob/0585ace85f42d07cadded093069e85d852e9b30a/vaadin-upload.html#L621)):*
Oh, one more thing. I changed my mind, and now think that file type validation on dragover is not worth it. Sorry.

It introduces inconsistency. `accept` might declare file name restrictions, and we can’t check them on `dragover`. This might cause no feedback while the files are still acceptable.

Would be better to go with only `maxFiles` check.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[vaadin-upload.html, line 621 \[r4\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35#-KCKbZx_T8SoBdNmNUmL:-KCKpZZg7nD6_izT3i_Q:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/0585ace85f42d07cadded093069e85d852e9b30a/vaadin-upload.html#L621)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/35)*

**Pull request merged**
