### PR TITLE
Prepare for the P3 conversion

### LINKED ISSUE #257: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #257

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/261)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[wct.conf.js, line 11 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261#-L8gvpsO7HUHl7Ei8dt8:-L8gvpsO7HUHl7Ei8dt9:b-rxzl7j) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2e41c3880192d6d310ff2f629412d56e4c7c3ca4/wct.conf.js#L11)):*
> ```JavaScript
>       'Windows 10/internet explorer@11',
>       'macOS 10.12/safari@11.0',
>       'macOS 9.3.2/iphone@9.3'
> ```

Was this intentionally removed?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 14 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261#-:-L8gwNmY81GIfH9RxuCf:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[bower.json, line 40 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261#-L8gxMow2OYCkU32YjtO:-L8gxMow2OYCkU32YjtP:bdmwvb6) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f5137122ecbe010cfd0d7b985a9225f651b846e4/bower.json#L40)):*
> ```JSON
>     "iron-demo-helpers": "^2.0.0",
>     "iron-test-helpers": "^2.0.0",
>     "mock-http-request": "abuinitski/MockHttpRequest#npm_fix",
> ```

This dependency doesn't end up in package.json on conversion so none of the demos seem to work.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[bower.json, line 40 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261#-L8gxMow2OYCkU32YjtO:-L8hWXP1-r8Yq2x2fqSy:b-zhbfqj) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f5137122ecbe010cfd0d7b985a9225f651b846e4/bower.json#L40)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This dependency doesn't end up in package.json on conversion so none of the demos seem to work.
</blockquote></details>

You need to upgarde `magi-cli` to 0.5.1 to get it working
I've added the mapping in platosha/magi-cli@7dfd39e

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261)*

**Comment by tomivirkki** [comment]
*[bower.json, line 40 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261#-L8gxMow2OYCkU32YjtO:-L8hiS4X-O2BaUPTIB7J:bfc1bd2) ([raw file](https://github.com/vaadin/vaadin-upload/blob/f5137122ecbe010cfd0d7b985a9225f651b846e4/bower.json#L40)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

You need to upgarde `magi-cli` to 0.5.1 to get it working
I've added the mapping in platosha/magi-cli@7dfd39e
</blockquote></details>

Ah, so it seems. Works fine now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261)*

**Comment by web-padawan** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[wct.conf.js, line 11 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261#-L8gvpsO7HUHl7Ei8dt8:-L8homKMCjEhD4rPdb0s:b-yc7wcp) ([raw file](https://github.com/vaadin/vaadin-upload/blob/2e41c3880192d6d310ff2f629412d56e4c7c3ca4/wct.conf.js#L11)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Was this intentionally removed?
</blockquote></details>

My bad. Restored the Safari 9, will check the origin from where I copied this later. Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 13 of 15 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261#-:-L8kI7Sm2ZHW0Lr3xukZ:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 13 of 15 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-upload/261)*

**Pull request merged**
