### PR TITLE
Added files property, file list and file element

### PR DESCRIPTION
**Pull request by platosha**
connected to #1

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/11)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 59 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/11#-K9lM2M8H2duWQMG5py7:-K9lM2M8H2duWQMG5py8:-485325981) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5c73af46f5740b8a739a6cf419460b8ec3b2a289/vaadin-upload.html#L59)):*
Could you enclose this with content something like:

```
  <template is="dom-repeat" items="[[files]]">
     <content select=".file>
        <vaadin-upload-file file="[[item]]"></vaadin-upload-file>
     </content>
  </template>
```

So as the user could have the option to do something like:

```
<vaadin-upload>
   <paper-progress class="file" max="[[file.size]] value="[[file.upload]]"></paper-progress>
</vaadin-upload>
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/11)*

**Comment by platosha** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-upload.html, line 59 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-upload/11#-K9lM2M8H2duWQMG5py7:-K9ljRM2Og3NAakR0vEJ:-499146009) ([raw file](https://github.com/vaadin/vaadin-upload/blob/5c73af46f5740b8a739a6cf419460b8ec3b2a289/vaadin-upload.html#L59)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/11)*

**Comment by manolo** [comment]
Reviewed 3 of 5 files at r1, 3 of 3 files at r2.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/11)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-upload/11)*

**Pull request merged**
