### PR TITLE
Fix Polymer 1.x dependencies. Downgrade demos to ES5 syntax

### LINKED ISSUE #229: "vaadin-themable-mixin": "^1.1.0" requires Polymer 2 which leads to ECONFLICT Unable to find suitable version for polymer
https://github.com/vaadin/vaadin-upload/blob/4bb3955f3dd364441cf8004b67d62dfd86173faa/bower.json#L39

When you try to 'bower install --save vaadin/vaadin-upload#^2.1.2' or bower install --save vaadin/vaadin-upload on an Polymer 1 project it will result in an error.

My tmp workaround is via .bowerrc and
`"ignoredDependencies": [
		"vaadin-themable-mixin"
	]`

Best regards
Wenzel

### PR DESCRIPTION
**Pull request by manolo**
Fixes #229

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/230)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r1, 5 of 6 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 3 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/230#-Kyp3R780hPwhfL7gMmJ:-Kyp3R780hPwhfL7gMmK:b-7amu5e) ([raw file](https://github.com/vaadin/vaadin-upload/blob/4bb3955f3dd364441cf8004b67d62dfd86173faa/package.json#L3)):*
> ```JSON
> {
>   "name": "vaadin-upload",
>   "version": "2.1.2",
> ```

This should be left untouched for 2.x

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/230)*

**Comment by manolo** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 3 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/230#-Kyp3R780hPwhfL7gMmJ:-KypEZAi50XAiIWDqNh5:bbypsr1) ([raw file](https://github.com/vaadin/vaadin-upload/blob/4bb3955f3dd364441cf8004b67d62dfd86173faa/package.json#L3)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

This should be left untouched for 2.x
</blockquote></details>

A mistake when merging this file from master, Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/230)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/230)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/230#-:-KypmnYmOkwGo7CJUBpR:bnfp4nl)*

**Pull request merged**
