### PR TITLE
Upgrade to pure polymer 2

### PR DESCRIPTION
**Pull request by samiheikki**
Connects to #190

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-upload/219)

### CODE REVIEW

**Comment by manolo** [comment]
- remove `&dom=shadow` from test/index.html
- when `nodrop` is set, the drop files here, is still shown
- 

---

Review status: 0 of 40 files reviewed at latest revision, 10 unresolved discussions.

---

*[vaadin-upload-file.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-8XNRC3U9LyiEo6V1:-Kw-8XNRC3U9LyiEo6V2:b-2wgehm) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload-file.html#L8)):*
> ```HTML
> 
> <link rel="import" href="../polymer/polymer-element.html">
> <link rel="import" href="../polymer/lib/mixins/gesture-event-listeners.html">
> ```

I think we can remove gesture dependency

---

*[vaadin-upload-file.html, line 109 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-8c7sIg8vEQ81vXUr:-Kw-8c7sIg8vEQ81vXUs:b78b1ua) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload-file.html#L109)):*
> ```HTML
>        * @demo demo/index.html
>        */
>       class VaadinUploadFile extends Vaadin.ThemableMixin(Polymer.GestureEventListeners(Polymer.Element)) {
> ```

Remove gesture

---

*[vaadin-upload-file.html, line 134 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-8lFR2Kd4zsMHXhom:-Kw-8lFR2Kd4zsMHXhon:b-ayb5qe) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload-file.html#L134)):*
> ```HTML
>         _remove() {
>           this.dispatchEvent(
>             new CustomEvent('file-remove', {
> ```

Nit: I'd rather have this in one line, since does not aport any readability improvement, and less lines makes easier to navigate the code. not a blocker

---

*[vaadin-upload-styles.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-ASUbot2tys3wKGxx:-Kw-ASUbot2tys3wKGxy:bmk18og) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload-styles.html#L18)):*
> ```HTML
> </style>
> 
> <dom-module id="vaadin-upload-default-theme" theme-for="vaadin-upload">
> ```

I think we don't need to maintain this empty block, since default theme is not needed to have, themable-mixin just ignores it if it does not exist.

---

*[vaadin-upload.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-ArLDqf4uedebhMzW:-Kw-ArLDqf4uedebhMzX:b-l6mwxj) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L8)):*
> ```HTML
> 
> <link rel="import" href="../polymer/polymer-element.html">
> <link rel="import" href="../polymer/lib/mixins/gesture-event-listeners.html">
> ```

remove

---

*[vaadin-upload.html, line 40 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-6Ck786PInQYNQNH5:-Kw-6Ck786PInQYNQNH6:bcjgnm8) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L40)):*
> ```HTML
>       [part="drop-label-icon"] {
>         font-family: 'vaadin-upload-icons';
>         margin: 0 1em;
> ```

Probably this might be applied to the slotted content, otherwise the customized demo should have some rule so as there is some spacing 

---

*[vaadin-upload.html, line 117 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-AoPDCaLFId9Ms0e2:-Kw-AoPDCaLFId9Ms0e3:byrecj6) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L117)):*
> ```HTML
>        * @demo demo/index.html
>        */
>       class VaadinUpload extends Vaadin.ThemableMixin(Polymer.GestureEventListeners(Polymer.Element)) {
> ```

Remove Gesture

---

*[vaadin-upload.html, line 518 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-B18kjQgVC4oNaUWK:-Kw-B18kjQgVC4oNaUWL:b-ecfncd) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L518)):*
> ```HTML
>         uploadFiles(files) {
>           files = files || this.files;
>           files = files.filter((file) => {
> ```

unneeded brackets, use one line

---

*[vaadin-upload.html, line 596 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-BA1zbXSraD6Ra93F:-Kw-BA1zbXSraD6Ra93G:b-ubxm8w) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L596)):*
> ```HTML
>               file.complete = !file.error;
>               this.dispatchEvent(
>                 new CustomEvent(`upload-${file.error ? 'error' : 'success'}`, {
> ```

Collapse in one line, there are more cases below 

---

*[demo/upload-basic-demos.html, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-KvzyxPW86t-CxvuEkMR:-KvzyxPW86t-CxvuEkMS:b-yjrp62) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/demo/upload-basic-demos.html#L69)):*
> ```HTML
> 
>         <script>
>           window.addDemoReadyListener('#upload-basic-demos-setting-restrictions-on-files-to-upload', function(document) {
> ```

Nit: use arrow functions (also in other demos). Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-:-KvzzVWZYbnQCMOqx6XN:bfixme7)*

**Comment by limonte** [comment]
Great job @samiheikki! :muscle: 

I fixed visual tests, please pull my commits.

**Comment by limonte** [comment]
Review status: 0 of 41 files reviewed at latest revision, 9 unresolved discussions.

---

*[vaadin-upload.html, line 596 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-BA1zbXSraD6Ra93F:-Kw-vwXeO3dE8VmggaMu:b-i80h8m) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L596)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Collapse in one line, there are more cases below 
</blockquote></details>

This is the matter of taste and should not be discussed in CR. Sami's coding style is just fine and more readable than one-liners.

---

*[vaadin-upload.html, line 92 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-vFbRbyDbhkf6bw3B:-Kw-vFbRbyDbhkf6bw3C:b-mdwahe) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1e2b4f63ae05dd830b0298a8e18780f2a03aa806/vaadin-upload.html#L92)):*
> ```HTML
>        * Part name | Description | Theme for Element
>        * ----------------|----------------|----------------
>        * `primary-buttons` | Upload container | vaadin-upload
> ```

Could you please make this table more readable with spaces, many folks look into source code instead of API docs page. Something like this: https://github.com/vaadin/vaadin-checkbox/blob/master/vaadin-checkbox.html#L91

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219)*

**Comment by limonte** [comment]
Review status: 0 of 41 files reviewed at latest revision, 8 unresolved discussions.

---

*[vaadin-upload.html, line 92 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-vFbRbyDbhkf6bw3B:-Kw-w_H4WEKGe-w9lIVm:b-nevucu) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1e2b4f63ae05dd830b0298a8e18780f2a03aa806/vaadin-upload.html#L92)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Could you please make this table more readable with spaces, many folks look into source code instead of API docs page. Something like this: https://github.com/vaadin/vaadin-checkbox/blob/master/vaadin-checkbox.html#L91
</blockquote></details>

Not a blocker though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219)*

**Comment by limonte** [comment]
Just a one small optional detail to change, everything else is great :lgtm:  

---

Review status: 0 of 41 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-:-Kw-wfmpP1f2d3oaxKKj:bm6vjya)*

**Comment by samiheikki** [comment]
Fixed `nodrop` attribute with hidden `drop files here` text

---

Review status: 0 of 45 files reviewed at latest revision, 10 unresolved discussions.

---

*[vaadin-upload-file.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-8XNRC3U9LyiEo6V1:-Kw0bBaRGcwimOELldey:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload-file.html#L8)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think we can remove gesture dependency
</blockquote></details>

Done.

---

*[vaadin-upload-file.html, line 109 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-8c7sIg8vEQ81vXUr:-Kw0bChJxPR7gcMQb1Z9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload-file.html#L109)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Remove gesture
</blockquote></details>

Done.

---

*[vaadin-upload-styles.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-ASUbot2tys3wKGxx:-Kw0bItFSbNVGN-aETsy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload-styles.html#L18)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think we don't need to maintain this empty block, since default theme is not needed to have, themable-mixin just ignores it if it does not exist.
</blockquote></details>

Done.

---

*[vaadin-upload.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-ArLDqf4uedebhMzW:-Kw0bRMuS9H1B8MxHf85:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L8)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[vaadin-upload.html, line 40 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-6Ck786PInQYNQNH5:-Kw0bacISfisc79cLJnR:b-hen0ke) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L40)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Probably this might be applied to the slotted content, otherwise the customized demo should have some rule so as there is some spacing 
</blockquote></details>

Should I remove it or move to styles?

---

*[vaadin-upload.html, line 117 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-AoPDCaLFId9Ms0e2:-Kw0bf1PIlpTzsTzWfLq:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L117)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Remove Gesture
</blockquote></details>

Done.

---

*[vaadin-upload.html, line 518 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-B18kjQgVC4oNaUWK:-Kw0brdRmOfr4gENKjum:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L518)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

unneeded brackets, use one line
</blockquote></details>

Done.

---

*[vaadin-upload.html, line 596 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-BA1zbXSraD6Ra93F:-Kw0akQhUrECydWQe4Oa:bfrw5yw) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L596)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

This is the matter of taste and should not be discussed in CR. Sami's coding style is just fine and more readable than one-liners.
</blockquote></details>

Can you discuss it privately and come back with an answer :) I'm to happy to change them if needed.

---

*[vaadin-upload.html, line 92 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-vFbRbyDbhkf6bw3B:-Kw0beBz5sqW1ML7IX1E:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/1e2b4f63ae05dd830b0298a8e18780f2a03aa806/vaadin-upload.html#L92)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Not a blocker though
</blockquote></details>

Done.

---

*[demo/upload-basic-demos.html, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-KvzyxPW86t-CxvuEkMR:-Kw0azgrxa6SnwV_pcYE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/demo/upload-basic-demos.html#L69)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Nit: use arrow functions (also in other demos). Not a blocker.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-:-Kw0fWkVJhiaA6V6XT6-:bv5zjx2)*

**Comment by tomivirkki** [comment]
Review status: 0 of 45 files reviewed at latest revision, 11 unresolved discussions.

---

*[vaadin-upload-file.html, line 196 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw1IkLqD4RRrFWWeQp1:-Kw1IkLqD4RRrFWWeQp2:bsc6bj9) ([raw file](https://github.com/vaadin/vaadin-upload/blob/62eeff36e998fa53a415586da4d09ec9043df872/vaadin-upload-file.html#L196)):*
> ```HTML
>        */
>       window.Vaadin = window.Vaadin || {};
>       Vaadin.VaadinUploadFile = VaadinUploadFile;
> ```

To unify naming with other Vaadin elements, this should be `Vaadin.UploadFileElement`

---

*[vaadin-upload.html, line 20 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw1JD4Ym4rTIJCOT578:-Kw1JD4Ym4rTIJCOT579:b9cd37v) ([raw file](https://github.com/vaadin/vaadin-upload/blob/62eeff36e998fa53a415586da4d09ec9043df872/vaadin-upload.html#L20)):*
> ```HTML
>         display: block;
>         position: relative;
>         text-align: left;
> ```

text-align could be moved to the default theme

---

*[vaadin-upload.html, line 29 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw1JIH6ZjalSgkFnVS7:-Kw1JIH6ZjalSgkFnVS8:b3rtuk4) ([raw file](https://github.com/vaadin/vaadin-upload/blob/62eeff36e998fa53a415586da4d09ec9043df872/vaadin-upload.html#L29)):*
> ```HTML
>       :host(:not([nodrop])) {
>         border: 1px dashed;
>         padding: 1em;
> ```

at least border and padding could be moved to the default theme

---

*[vaadin-upload.html, line 897 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw1JdjGbteK-LIWNc-T:-Kw1JdjGbteK-LIWNc-U:b-7p7nef) ([raw file](https://github.com/vaadin/vaadin-upload/blob/62eeff36e998fa53a415586da4d09ec9043df872/vaadin-upload.html#L897)):*
> ```HTML
>        */
>       window.Vaadin = window.Vaadin || {};
>       Vaadin.VaadinUpload = VaadinUpload;
> ```

To unify naming with other Vaadin elements, this should be `Vaadin.UploadElement`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219)*

**Comment by manolo** [comment]
Review status: 0 of 45 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-upload.html, line 40 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-6Ck786PInQYNQNH5:-Kw22kfcAh5-oO_HR99P:b-5o55zd) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L40)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Should I remove it or move to styles?
</blockquote></details>

Well, imo this block should be in the default theme.
but additionally you need to  target also the slotted in this block,  or set a margin in the demo, I don't have a strong preference

---

*[vaadin-upload.html, line 596 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-BA1zbXSraD6Ra93F:-Kw23PEfFXiN2IcpCBUG:b6mzx3j) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L596)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Can you discuss it privately and come back with an answer :) I'm to happy to change them if needed.
</blockquote></details>

because it is a matter of taste, I did leave this comment as resolved in order not block the PR nor start any discussion.  It was just my suggestion, less code means less lines of code, more performance and much easier to read trivial blocks since you don't have to scroll to have more visual area. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219)*

**Comment by manolo** [comment]
Reviewed 25 of 40 files at r1, 10 of 12 files at r2, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219)*

**Comment by samiheikki** [comment]
Review status: 41 of 45 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-upload-file.html, line 196 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw1IkLqD4RRrFWWeQp1:-Kw6HXsWB21Lfz7shpp2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/62eeff36e998fa53a415586da4d09ec9043df872/vaadin-upload-file.html#L196)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

To unify naming with other Vaadin elements, this should be `Vaadin.UploadFileElement`
</blockquote></details>

Done.

---

*[vaadin-upload.html, line 40 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw-6Ck786PInQYNQNH5:-Kw6J2QXqH38b6Lpf27b:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/53e53431aa97067fa12989c2e3c1d43a41ddadc4/vaadin-upload.html#L40)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Well, imo this block should be in the default theme.
but additionally you need to  target also the slotted in this block,  or set a margin in the demo, I don't have a strong preference
</blockquote></details>

Done.

---

*[vaadin-upload.html, line 20 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw1JD4Ym4rTIJCOT578:-Kw6ISQYI-sJmpvWQbkR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/62eeff36e998fa53a415586da4d09ec9043df872/vaadin-upload.html#L20)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

text-align could be moved to the default theme
</blockquote></details>

Done.

---

*[vaadin-upload.html, line 29 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw1JIH6ZjalSgkFnVS7:-Kw6I_088XQHxSQC2zvW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/62eeff36e998fa53a415586da4d09ec9043df872/vaadin-upload.html#L29)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

at least border and padding could be moved to the default theme
</blockquote></details>

Done.

---

*[vaadin-upload.html, line 897 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-Kw1JdjGbteK-LIWNc-T:-Kw6J5Cuv4Ad_jXMdqC8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-upload/blob/62eeff36e998fa53a415586da4d09ec9043df872/vaadin-upload.html#L897)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

To unify naming with other Vaadin elements, this should be `Vaadin.UploadElement`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219)*

**Comment by manolo** [comment]
:lgtm: Good job!, thank @samiheikki

---

Reviewed 4 of 4 files at r4.
Review status: 44 of 45 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-:-Kw8pui6T_PQegF1Pbki:b49o145)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219)*

**Comment by tomivirkki** [comment]
:lgtm: Superb!

---

Reviewed 24 of 40 files at r1, 10 of 12 files at r2, 6 of 10 files at r3, 4 of 4 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-upload/219#-:-Kw9VdMidWLpcwyaxBt6:b-od01px)*

**Pull request merged**
